#
# Sample .travis.yml using the mvp-helloworld image (a helmoperator)
#
os:
  - linux

language: go
go:
  - "1.13.x"

services:
  - docker

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "opo/uIdMEn/VZkAGh8PSPSokyeWRHSx9fxWFLeU3KNGshKfoMloCtphtc06xkrqKpk27UmiE72F7wJ7U5NMM9OCyFJEROSeznuAunN/mjy2J1y1lOOJk3yX4WlD98xXxML8S901Ke457VVFj+VPRdUhXtGIzCtNu0WzFng3JbhPmAuvxYyM/blGgWR1Utsx5+huF3CoTcsw9kXHp/3rjgm8ggXw0FyLdhQZELHeb+6tt7bDtq0pCbScBJib5wu7pl7MgMAd0rI585VSBVHz0qF0xeQlb2ptIeuCgv5ar7Lez070O0r984zqU06RveCNVlUezKiao01iSQPBmKMj3/e7QtfTRvOquVgZCLW8dYLUlXXxTuOlAYSLr7GiuUUSpKcm4W9oCJW4Bu90w57GIsNqmeyU4Extnn8DZUxQklezOq9ig2xFpCMP5FwXBvk3rePCB/MJiJrqElKt+ysp/+WB3aO0dXJYQBjRBERdB4J4P72eNgh4KpPgxK7M74t6/C2AF/x43yZWFLL2ffYzMdgqFddCMeSlakR+74+BpzYdOj0e8cMEJnBggpjDFRwT2NWzXkoJkvA+dLauO/HsVSl6qOdEzE/v0s03+Wj6rhL6QRG1/ck+/Y4I93rDRfLIC8AQHjp+JhlyiRMX/xzv0VrngKhrM0aFh5SNSpBxZQBg="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/unit-test.sh
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/deploy-to-cluster.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/e2e-test.sh

script:
  - echo "test travis"


if: type = pull_request
script: 
  - git clone --single-branch --branch dev-auto https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
  - cd multicloudhub-repo
  - ./cicd-scripts/chartAutomation.sh search-chart