#
# Sample .travis.yml using the mvp-helloworld image (a helmoperator)
#
os:
  - linux

language: go
go:
  - "1.13.x"

services:
  - docker

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "opo/uIdMEn/VZkAGh8PSPSokyeWRHSx9fxWFLeU3KNGshKfoMloCtphtc06xkrqKpk27UmiE72F7wJ7U5NMM9OCyFJEROSeznuAunN/mjy2J1y1lOOJk3yX4WlD98xXxML8S901Ke457VVFj+VPRdUhXtGIzCtNu0WzFng3JbhPmAuvxYyM/blGgWR1Utsx5+huF3CoTcsw9kXHp/3rjgm8ggXw0FyLdhQZELHeb+6tt7bDtq0pCbScBJib5wu7pl7MgMAd0rI585VSBVHz0qF0xeQlb2ptIeuCgv5ar7Lez070O0r984zqU06RveCNVlUezKiao01iSQPBmKMj3/e7QtfTRvOquVgZCLW8dYLUlXXxTuOlAYSLr7GiuUUSpKcm4W9oCJW4Bu90w57GIsNqmeyU4Extnn8DZUxQklezOq9ig2xFpCMP5FwXBvk3rePCB/MJiJrqElKt+ysp/+WB3aO0dXJYQBjRBERdB4J4P72eNgh4KpPgxK7M74t6/C2AF/x43yZWFLL2ffYzMdgqFddCMeSlakR+74+BpzYdOj0e8cMEJnBggpjDFRwT2NWzXkoJkvA+dLauO/HsVSl6qOdEzE/v0s03+Wj6rhL6QRG1/ck+/Y4I93rDRfLIC8AQHjp+JhlyiRMX/xzv0VrngKhrM0aFh5SNSpBxZQBg="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/unit-test.sh
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/deploy-to-cluster.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/cicd-scripts/e2e-test.sh

stages:
  - build
  - unit-test
  - test-e2e
  - publish

jobs:
  include:
    - stage: build
      name: "Build the test image and push it"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make
        - make component/build
        - make component/push
        - git commit -m "[skip ci] skip travis"
        - git push origin $TRAVIS_PULL_REQUEST_BRANCH
        - make security/scans
    - stage: unit-test
      name: "Run unit tests"
      if: type = pull_request
      script:
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.  
        - | 
          make 
          make component/pull 
          make component/test/unit 
          make sonar/go
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make 
          make component/pull 
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - |
          make 
          make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
