apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:51:38.767344981Z"
    description: Helm chart for Open Cluster Management application UI
    digest: c5a513eae6df75457cc7c321fec5c0bb79e7f8720d7f3da9e4155fb07f1d3f3e
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T19:51:38.770596496Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: b8977e1277c9fa881d7c05a68b584c51e4aa28a72ea30c3faad53b35091edc64
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T19:51:38.771963617Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 3c4eacc77b38f52c361ed4e537249266ce58db16bc10edb33200830fb8aace64
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-04T19:51:38.773021263Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 13925d17e27324794e0e86a245d3a7aa95e1d6b633dc7473a86e42c070b5b4d3
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:51:38.775054846Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 0cab9ce062a4d3b3f3338f51327a88ac4bafb8ad9ae853e5bcb1a47713581f3a
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:51:38.776234357Z"
    description: helm chart for multicloud grc
    digest: 0c17d1640194cf03cd7a43910d62ec8c9c4457937ea439cb43b9f3461985e3b9
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T19:51:38.776936849Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 879d97afbd2dac926145a4c13919af7a89daab1bb7382793afc708902e158ca2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T19:51:38.777911634Z"
    description: Multi Cloud control plane ingress controller
    digest: 14a8a913e8ee53cf3109c539c11afcf9e3ff6289b29ef4193065c2b229ec2ac2
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T19:51:38.778475279Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 4f320a068d6d859865d086ef981a4a266912f4a6b7007adedb5e39c231ccff40
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T19:51:38.779487131Z"
    description: Helm chart to install the Multicloud Search service
    digest: 7989a7819fc715cd5453b4f85738dc963678d39dfaeb460fe81a51267fd9f68f
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:51:38.779995744Z"
    description: helm chart for multicloud topology
    digest: c91acaaef77d69f12f8161cb3371c257c579e853d8a53586ca373ee54ec0e935
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-04T19:51:38.766590439Z"
