apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:32:21.059152345Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 40439e255399b3d6cbb76cd54f971d238807bd2d34d79544830383241cbf7270
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-05T14:32:21.062444726Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 4bf85f6e49b773a8acb9b9264d11ce793bdcd7deaa8af4923c5e50e078fe3560
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-05T14:32:21.063824448Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 85ad8d352c58e67ce340f2ea1c7703f62021db1b7f4ff88a00dd428ddb1440fd
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-05T14:32:21.065488632Z"
    description: A helm chart for deploying the config map watcher component.
    digest: b5c8a3c71a201bb9d5dbebbddf1940cbeb37d2a73e68b652cecf0c25c08fa214
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:32:21.067328876Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: fafc8eced55a9ba827dc4ab927b8b784c8bf8fc7fba67b53967e3cef3ba3f7f5
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:32:21.068021317Z"
    description: helm chart for multicloud grc
    digest: a1f6f308c337631c6b331c079c65825ad9c59852df4ae1accc9dd16e9740bc91
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-05T14:32:21.068691683Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 88943437b13f708a9ff02e82c12be584e81a6031fdc41caf84a92db39c6f60ba
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-05T14:32:21.069513501Z"
    description: Multi Cloud control plane ingress controller
    digest: 57fcd8d889e6374b95c03c1a5675748001d0c5fa95c2d1e3b7634e2cc0a1fe5d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-05T14:32:21.070055432Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: fbfe7028f91a85d2d7c277514d340afa4167369bfbf800223fc39d47c88c9e3b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-05T14:32:21.07097157Z"
    description: Helm chart to install the Multicloud Search service
    digest: 18a7a2f6682adb9a0808fd10c50a7daa37a78340e84a28744e29f88505304e37
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:32:21.071383438Z"
    description: helm chart for multicloud topology
    digest: 77912b8890fbc5089cc411f17c1fbde880b452cb53fbd4491c01c6a944c87fad
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-05T14:32:21.058636417Z"
