apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-09T10:52:26.057461-04:00
    description: Helm chart for Open Cluster Management application UI
    digest: 0dcbc3b210d5a47a18e94e8184cf8fae5ca6d5481929528093bbacaa97414192
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-09T10:52:26.060888-04:00
    description: Service for issuing and managing certificates.
    digest: a9fa0a83978ba52f12f08f910fed0b4484d3f7803963cbf4f7eadd284d923a80
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-09T10:52:26.062097-04:00
    description: A Helm chart for deploying the cert-manager webhook component
    digest: ec658f60777d0d9742595574eb001e8e9f70609ea6bca1f078cb03a872a33528
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: 2020-03-09T10:52:26.062816-04:00
    description: A helm chart for deploying the config map watcher component.
    digest: e17f64978b315dd7cf04be8ae32188a129ccca685a1e70876d3c8dc5f164ce5a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    tillerVersion: '>=2.7.0'
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-09T10:52:26.06429-04:00
    description: Helm chart for Open Cluster Management console UI
    digest: c1670c7ad0dde9d1d4d23c43c9a337af7eecf0e835f5080b4b11713f957fac8b
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multicloudhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-09T10:52:26.06475-04:00
    description: helm chart for multicloud grc
    digest: e51ed137a7009de03fb8f1fa333fab840670e6752efb675c09881a02334f0673
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-09T10:52:26.065824-04:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 6c2fde5b0a0633ceae3f154d1d761310b88358eaecaedb3ea9b6244fa545a633
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - appVersion: 3.4.0
    created: 2020-03-09T10:52:26.066677-04:00
    description: Multi Cloud control plane ingress controller
    digest: 27884c8adaf92348f4c2489eebdbc9a4250aedf1e3ef935ba69cec3151712b97
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-09T10:52:26.067221-04:00
    description: A helm chart for deploying the cluster lifecycle
    digest: d94f65a9f2dcb0120d7f420a7945b8796fa9097c3a0e79032bbdecccd3f552aa
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    tillerVersion: '>=2.12.3'
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - appVersion: 3.4.0
    created: 2020-03-09T10:52:26.068411-04:00
    description: Helm chart to install the Multicloud Search service
    digest: e933ec3526535ed0af630e1e59f1c09e0335addf0e93fbffd03173bf4172fc17
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-09T10:52:26.06886-04:00
    description: helm chart for multicloud topology
    digest: ca4ed664779fc6c6b44538c7e814ca8fe0fd9dd4145ae19bb9c7d170dbe548c6
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: 2020-03-09T10:52:26.05584-04:00
