apiVersion: v1
entries:
  ibm-cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-02-14T10:10:06.196982954-05:00
    description: Service for issuing and managing certificates on IBM Cloud Private.
    digest: 60894cc153e8b25746c2b15b484e8072c39d8b031e128d824cd2c165e4b5d1e8
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - ICP
    - IcpClusterResource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - IBM Cloud Private
    - ICPRHOCP
    - RHOCP
    - ROKS
    - ICPROKS
    kubeVersion: '>=1.11.0'
    name: ibm-cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - ibm-cert-manager-3.5.0.tgz
    version: 3.5.0
  ibm-search-prod:
  - appVersion: 3.4.0
    created: 2020-02-14T10:10:06.197928024-05:00
    description: Search Helm Chart for IBM Cloud Pak for Multicloud Management
    digest: 8e2dd7a7d2397854e97924b7ba8190385ab55c094f3360458d88decdd081a8eb
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicluster
    - search
    - Commercial
    - amd64
    - ppc64le
    - s390x
    - runtime
    kubeVersion: '>=1.10.0'
    name: ibm-search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - ibm-search-prod-3.5.0.tgz
    version: 3.5.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-14T10:10:06.19865457-05:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 8d7f8464ed4d01f6d9aa466bd1dbb7b2d031d42525856487a655ec23e81baf91
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
generated: 2020-02-14T10:10:06.192337916-05:00
