apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T14:15:30.469354009Z"
    description: Helm chart for Open Cluster Management application UI
    digest: bc4b9f34aeb2771c863008df15bf4b3bb7b9438bcd5a33298928c2b91dd8746a
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T14:15:30.472775399Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: e7108aa18dfeee0724556d3b7976bf360cdf2b2b9c539213488780a2d80141c5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T14:15:30.474202942Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 965dd6758ee81a2d4f321a00bdad56a3fbb56ec4c33fe2796a3a20158ad570d2
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-10T14:15:30.475591264Z"
    description: A helm chart for deploying the config map watcher component.
    digest: b5656536805423d67d9772ad169a58fd1e5bd646a3658fc433ad50c8aca9e1dc
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T14:15:30.477483018Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 4c66a45586809a1529123298417ebfa9e8e0096347ae228731b7c3438b2dd0a1
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T14:15:30.478670094Z"
    description: helm chart for multicloud grc
    digest: 3b164c31928394344378098327f0e5dbcf7d5336123f0a77a36405d50f76ab6b
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T14:15:30.479364295Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 57e7d7d5c957874f25c9c7a02b000ed70c1230774c44e2e8cfe9971d7883f672
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T14:15:30.480210604Z"
    description: Multi Cloud control plane ingress controller
    digest: 3f851dd570675fc4cbb02e20060f74c5b2d2f8e1f4e0fabd48d838cc058ab855
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-10T14:15:30.482296981Z"
    description: NoSQL document-oriented database.
    digest: e0d2549e179081afffa33d2bc4ae1b0322fba65b8e74109c9c92847ebfd73abd
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T14:15:30.482893048Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: ca559e83f770f0b969f2ff626e47ae2524b1ce5d6488dcf4b34bfe813dde6359
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T14:15:30.483833591Z"
    description: Helm chart to install the Multicloud Search service
    digest: 20ba68fec5b2fd90e28079e9b62b3ff26be3e9951974e001088340d7a8e19e69
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T14:15:30.484289473Z"
    description: helm chart for multicloud topology
    digest: c3225d875fb801da9f43aa4bc9810028d2bc3ff6a88b2b6c049135c72d842747
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-10T14:15:30.468738523Z"
