apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T11:03:15.923228-04:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 48769d3c84e9a2688f99bd94ae3f99fb944d8d107349993addf6328b5b079771
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T11:03:15.931051-04:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 48a5fc29c6ae2c1d53639c0d12aee2aed496dc5d64d31203a0ded6b9be746b4d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T11:03:15.932757-04:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 7469821d95c60fe8d6ded059400de382b9f5f49dfa382bc3d16459663dd88a7c
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-09T11:03:15.933758-04:00"
    description: A helm chart for deploying the config map watcher component.
    digest: e93a6890b49214cfc5b62b3ae985170c971bcfcb00d9ad91b79bcd33be49eef2
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T11:03:15.935914-04:00"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 2cf38d1edeb652ecd6d26cbefaa23a1eacbbd4bc4be65c78cfd590ed4536936d
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multicloudhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T11:03:15.937884-04:00"
    description: helm chart for multicloud grc
    digest: eb96fb0d714497c13735c58b682b85151dde291d07c849e356f650dacf6215fd
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T11:03:15.93937-04:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: f6ba9466418d421efd26eed512107fafff51366b188528eabe97c746c3b4dfe4
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T11:03:15.941517-04:00"
    description: Multi Cloud control plane ingress controller
    digest: 89aa882ff9ba9553b7920a64dde96beb10cf8e7c96dca51653c858de32fc85d8
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-09T11:03:15.944308-04:00"
    description: NoSQL document-oriented database.
    digest: c2d11480091b9428bd7b61ef2f47ea9cd988d004e5d219be4d2ff25820c9ef04
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multicloudhub-repo:3000/charts/multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T11:03:15.945115-04:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2e9fb160c1a3ccac6557f52d973224661bdb44f6a0d7a3a713752335fdce09ec
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T11:03:15.947912-04:00"
    description: Helm chart to install the Multicloud Search service
    digest: f3707b1ae755eb86d49cda26baba74941107e7fcf6618b98f6903e316aaaf643
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T11:03:15.948475-04:00"
    description: helm chart for multicloud topology
    digest: c5134d40355158d4f3b062476fa044e96b896e7b8171f05de24e9658a5892b10
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-09T11:03:15.922311-04:00"
