apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T16:07:23.254404982Z"
    description: Helm chart for Open Cluster Management application UI
    digest: be451d0e91f1d0886f09d2cc483af051369e5b0215234b69af094497f7c18129
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T16:07:23.258597283Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: b758ffd3d644362e7299a40cd39df3121b35757397558c7b85424dfa1018f4eb
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T16:07:23.260094247Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 98b4539974960044f8413fa2a95a2894d2058f0051b4bac1692c24cefb189e40
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-10T16:07:23.260901928Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 92b1b02e8230069a0d512a63885c23fc00d5c767bbf2648d91aa7209161ec454
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T16:07:23.262567259Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 1429bce0b6ef6763dcc2ea90c3374c218b6e07e860cc4f712322cdfce870742b
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T16:07:23.2637952Z"
    description: helm chart for multicloud grc
    digest: b7e0fcbda144265e21ba7105c2dc3711c41e3da0284778e7af95cc3ec14b5bc4
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T16:07:23.265334204Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: c1682cfd6b13085dddc27febd83616cafd9a68d96ced3415fdffbadcaa2c2f98
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T16:07:23.266554613Z"
    description: Multi Cloud control plane ingress controller
    digest: 94daeea15e2fb5f3fe9be37fbe1aa53c3a554062af10cbe04e8dfa24add9af54
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-10T16:07:23.268686216Z"
    description: NoSQL document-oriented database.
    digest: 8d22ff478272ca42d37cccd02c26528bd7f269b951fd4eb842dc1cbd3972aa71
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T16:07:23.269265812Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d31bbd644582d7ed70826c2cafad2a902bf23179d249aec2e60679a23179ef11
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T16:07:23.270293836Z"
    description: Helm chart to install the Multicloud Search service
    digest: ef8f7945eb8e33c0c964db45b74212015f420cb2a04c94d7d6b78e61b1e91ce0
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T16:07:23.270783445Z"
    description: helm chart for multicloud topology
    digest: 9d79ff158716214d953426ba4bd3955af2a5949ddd61242c6ae98c6ca5162c9a
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-10T16:07:23.253106139Z"
