apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:51:25.280396866Z"
    description: Helm chart for Open Cluster Management application UI
    digest: c445f582e3e2ca62f015a863da46769db05db51c6bfce4b8388f6a2820451558
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T15:51:25.283766399Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: bfa79f697d3887184b4796f5b7d66985ecc038293de58bf560db1bc166b5011a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T15:51:25.285221176Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c3f1191c7f6f966c2c96f6b2e205326f6095b19cacb33e8a115ff502f68fab30
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-09T15:51:25.286858254Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 672f99105d25dbb3fb6620a99145e39d5b559fb4646947bab9f0aaf4cba43add
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:51:25.288734634Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 39f34555d1ae6a71eef29718eb8dd2d1454bb71188da1a52d4ae85cd4742f993
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:51:25.289741369Z"
    description: helm chart for multicloud grc
    digest: 2ba1a8efa661e5cc053280385a8d0672bb9dc5153fc9d9629439f4e2a2ebe004
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T15:51:25.290433555Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 9c3b91a4bcf82e5264ed67b8a1248aa75251a2d882484c7331b8665f0ee8cc48
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T15:51:25.291253362Z"
    description: Multi Cloud control plane ingress controller
    digest: 19c3300122eccd9842e14d9221e1dccc9e1c524c117c0aae383b248ba21f7f79
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T15:51:25.291824166Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 06c77bf699739c4ddcf84072897ca6756e836d02078f0fc80dcf219a6985adbb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T15:51:25.292836443Z"
    description: Helm chart to install the Multicloud Search service
    digest: 4303069934d1366e2e7032efb38c1ae882ce1c1b11b823a956420071ebf66f6b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:51:25.293309966Z"
    description: helm chart for multicloud topology
    digest: 6733bf78f31042043ffc264dd2e4fa9443d0d8a6bbc28d2bd7f1018c9919e572
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-09T15:51:25.2798701Z"
