apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-24T08:10:27.752966-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 77f43a4a1f2ba11d119125653b499bf54cb74ffa510e38242f0904d72d77686e
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-24T08:10:27.754589-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 50171f3fd9678deda66cd1dda04c09177a926afdfb9511942c4680704a7f2e06
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-02-24T08:10:27.755533-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: f59a401ca70b5df52210548355a58b77f3aca44c2b650db9d8de58cf3dd54692
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T08:10:27.756187-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: 8e3ee1800b75f42969da88aa278fb48db071d3c8b6369b65104ce6ae15edf508
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T08:10:27.756915-05:00"
    description: helm chart for multicloud grc
    digest: 952054ee84f34a354a4c21629d66012165f41d9bb970dce11411a0a240414c68
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  ibm-search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-24T08:10:27.758413-05:00"
    description: Search Helm Chart for IBM Cloud Pak for Multicloud Management
    digest: 98054501d3cbc04081570864dd031f431d5f99a546d6b42fe15d5ca7a3051e53
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicluster
    - search
    - Commercial
    - amd64
    - ppc64le
    - s390x
    - runtime
    kubeVersion: '>=1.10.0'
    name: ibm-search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/ibm-search-prod-3.5.0.tgz
    version: 3.5.0
  icp-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-02-24T08:10:27.76223-05:00"
    description: NoSQL document-oriented database.
    digest: db0cb0bb9cdc0c509286b5e8db388e08d954f397be557f8166d6a1058038e059
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    - database
    - ICP
    kubeVersion: '>=1.9.0-0'
    name: icp-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multicloudhub-repo:3000/charts/icp-mongodb-3.5.0.tgz
    version: 3.5.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T08:10:27.763293-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 962f48fe8386ef2664a9265cc94241a01d9d0507bfdfae049c2342d3ba82e9ee
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-24T08:10:27.764559-05:00"
    description: Multi Cloud control plane ingress controller
    digest: b4e58f1b02e0edd6a9373cf0755ec5b153bc1f42f1e0e6b5090e1bfd3bcf2f47
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  mcmapplicationui:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T08:10:27.7652-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 3c26f2a4631fee8f6db16be4c7bebd62fff51e612441d4de8067839b4e41caee
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: mcmapplicationui
    urls:
    - http://multicloudhub-repo:3000/charts/mcmapplicationui-1.0.0.tgz
    version: 1.0.0
  nginx:
  - apiVersion: v1
    appVersion: 1.16.1
    created: "2020-02-24T08:10:27.766393-05:00"
    description: Chart for the nginx server
    digest: 3aab7f7549fbda960a36f47ce035173845adefad40d9f7423d10298db0eb7e13
    home: http://www.nginx.org
    icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: nginx
    sources:
    - https://github.com/bitnami/bitnami-docker-nginx
    urls:
    - http://multicloudhub-repo:3000/charts/nginx-5.1.6.tgz
    version: 5.1.6
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T08:10:27.767179-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: d581ad5618c4444d3541fdd74cb9be867ad9c2d13a081f61e4b631869a3282be
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
generated: "2020-02-24T08:10:27.748339-05:00"
