apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T18:23:05.340666532Z"
    description: Helm chart for Open Cluster Management application UI
    digest: fbd6728c95afd7aeb5b7762b9f9f20d473056132dfd3fa577db7f2b19b28ceb8
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T18:23:05.343928932Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 06bb2633d3bcd50f11bb277d69921c51375ae0d4b95597ffd61c368fa647ba9f
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T18:23:05.345459455Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: ae3cf1f62445cd41e7f5a638be44fbaeaa339eafb9112f0374ca113ddaa6cba7
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-04T18:23:05.346278524Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 03572636c0dd9f78ecfa3e8eebd919e0c07c6fbee59174f37d4403e37f9ed08a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T18:23:05.348114194Z"
    description: Helm chart for Open Cluster Management console UI
    digest: 07919c027cc0f503d33a5fcf61e9f41a1b61825077e68bfed3b359496e944e6b
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T18:23:05.349258548Z"
    description: helm chart for multicloud grc
    digest: 3c35ab14b2471b0d8be40dce9ba8c10052d523bfbc1fb2546500c1997ca44d2b
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T18:23:05.350716242Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 83aac035129e80d5f5f22bff1cb3c78f7518ca49e52d011b5f9d38caf1c9e0c7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T18:23:05.351537444Z"
    description: Multi Cloud control plane ingress controller
    digest: 654f8b291142c5acdc85644184a39b1d136855dea837754a11377058244d75c3
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T18:23:05.352231889Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: e82d7d56d55c97b32ef0c53b3f04a2dd055da3483a06e34accf94f2519022439
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T18:23:05.353168704Z"
    description: Helm chart to install the Multicloud Search service
    digest: 6fae86d83fa4d0a749304ddaafd8ad1531bc6da4391bf195348e3fe007677cde
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
generated: "2020-03-04T18:23:05.339395677Z"
