apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T12:42:00.379232511Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 49979f1862f77ec0212dc9d16a7e81796ef072293bbb9bd03f0f20e6219464f0
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-11T12:42:00.382707309Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 4f62d6872a44ebd559694462fd88e532bf783470ed7453bd49a4c8b78c94f1e4
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-11T12:42:00.384174194Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 7646250d350709a3bd72e25ca1585ff568b1423acf96e942fc88efdec3e87702
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-11T12:42:00.38564875Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7f99e0f489c5f4eb7114527ac2f9415c83c36fdacc5eeab80b61d53f31c3d0b0
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T12:42:00.387729375Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 933f2ea5210220414551661459ced7c768146e41e23d06cf6b024c0e4e4922ee
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T12:42:00.389097087Z"
    description: helm chart for multicloud grc
    digest: 15d412b350db241589f44ec2583c690eca39841a945a7b86dce7e4cfb2a42dc8
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-11T12:42:00.389854026Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 67c6b32db4e5f24d40ea88a064fb279621e580a86e6332267158655276c81489
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-11T12:42:00.390737922Z"
    description: Multi Cloud control plane ingress controller
    digest: 40e43f49ec57a5cac7ecaf218558b709567c25646950145f88acf4025d6fd3d5
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-11T12:42:00.392980229Z"
    description: NoSQL document-oriented database.
    digest: 6283f35703716ee6dfdf1ee84ea8bfd3f510b2710ef444146ca32f6c321dcdd0
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-11T12:42:00.393587723Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: cbfefdfc369c7845f847c100075c17fc978e41c7049e69f8d1cc9aa5e0de90c6
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-11T12:42:00.394563123Z"
    description: Helm chart to install the Multicloud Search service
    digest: b046e18bf119c9f7a84b4d7169e524fa4c7dbe7360a35201216b5708a0cd9a4f
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T12:42:00.395075985Z"
    description: helm chart for multicloud topology
    digest: 828e10cd3851e89ae954bc1a177392da887a33d8476b54695904cdef48900654
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-11T12:42:00.378478198Z"
