apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:34:21.848235505Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 459cf2d5c6ff938050d684f38e526d80f8d1f5ac36ef02f4083d3f9d63c410f0
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T15:34:21.851532665Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 8a48a425afe9f05870a4dc2c88ebbc02afc6ab43d72d45d5bfcb4eb972475838
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T15:34:21.853016222Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: fc710bb8e37f691dd3ee878c79be30bea9b169fcc9867920a343670d8d83e92e
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-09T15:34:21.853834045Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 515338ed809ad349ab09e5ca8d8536782f3ab8109786910ec13411e893acdd16
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:34:21.855716676Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: b5dc9fd3572efe49e7078a9336ba0b0b6ac0301108cb97e4b4a148727078ebc5
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:34:21.856849937Z"
    description: helm chart for multicloud grc
    digest: 7a8996901c9df2e2969ef1273868280820d2470d29d9fd0b49264cb522ba2176
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T15:34:21.858390004Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: c028b7b832cf3250b3d84f3bdbc9ff85db93138ccedf0952c64a9518c019a97d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T15:34:21.859269508Z"
    description: Multi Cloud control plane ingress controller
    digest: cc17fe87cd0a3a1f40ac64d26c12c494ca5a59fffc6d690ba10fa41543eb2591
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T15:34:21.859827625Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 8360d8ba65a0d5d6bca6136371e5d6090a20876526403c51c5b83f493c9ea985
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T15:34:21.860787653Z"
    description: Helm chart to install the Multicloud Search service
    digest: 96ca7493aff00a0807ec522538387bba39d912637c6a84e044bddad3ae2295ba
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T15:34:21.861229934Z"
    description: helm chart for multicloud topology
    digest: f2a898b91e01f15dd46160484b57b1047628e0199801a2cafb786e69cf6a5f86
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-09T15:34:21.847279Z"
