apiVersion: v1
entries:
  applicationui:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-25T13:28:24.548771-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 88b18129721d8d08bb5bcaa140aa91ca1ee9582f7da2b040f78db78616da2caa
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: applicationui
    urls:
    - http://multicloudhub-repo:3000/charts/applicationui-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-25T13:28:24.564245-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: b1e70ae08e77e9c6c9fdf8c0eb136725382f34bf612652b0ff05bb6fa0a9d219
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-25T13:28:24.567818-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 493b0dda25f06507e12377f3c226a5042164612fbed756becc4b8854ecc2c870
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-02-25T13:28:24.570148-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: c30a8f100fb91af239720ee5ed114620ccf212198b07be4df7135c9c74246280
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-25T13:28:24.571603-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: 59dbacc92eeb4d14934b091deee05d1d2beb83b297a2a7b255b2bf0c93d58cd7
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-25T13:28:24.573026-05:00"
    description: helm chart for multicloud grc
    digest: cb7fa85e0af37a3800e15c540f083abe59baf547bec483ca44b1ca78e04d4451
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-25T13:28:24.575074-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 741e129761b31f8a0a90be6c361377eed0eec31cacaf1f00dfe74f0115474ff6
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-25T13:28:24.577733-05:00"
    description: Multi Cloud control plane ingress controller
    digest: 063d1aac8c5dbfe291138761cde87afdc1f311d54f3b23f8d11ed1899fcf459e
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  nginx:
  - apiVersion: v1
    appVersion: 1.16.1
    created: "2020-02-25T13:28:24.581161-05:00"
    description: Chart for the nginx server
    digest: 3ba9234853853be3513ed103a0efd7b8f98f7b4bbc2c697ae4a5d9836379ee09
    home: http://www.nginx.org
    icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: nginx
    sources:
    - https://github.com/bitnami/bitnami-docker-nginx
    urls:
    - http://multicloudhub-repo:3000/charts/nginx-5.1.6.tgz
    version: 5.1.6
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-25T13:28:24.583118-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: 140a26f02c074389e51d23df78e06aaf547afb4ca7cb03a22ad4d5278ccd3c16
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-25T13:28:24.586667-05:00"
    description: Helm chart to install the Multicloud Search service
    digest: 43c6057775e35d2cc48bc1194a369ca68279805fd638fdc67e42363a6e99af1d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-25T13:28:24.588321-05:00"
    description: helm chart for multicloud topology
    digest: 2ffefa67c4b803ca544576cd8d9d97616aed8e716f462dd6838a30b187da84f3
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-02-25T13:28:24.545356-05:00"
