apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T20:06:16.768345572Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 3e483430ea5ff86c118abf765a5821bb249e332ef6bb796c9fc5c7edd9d0ab16
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T20:06:16.77174284Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: a76ce5e96b1fe71f164846d1e54709a57838d505c74d2e3ae0459b2b01ffa777
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T20:06:16.773184568Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 984f87d01a905a765c75bb400c601842feb1c1db786c2dfe5c453bc338cfe66a
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-04T20:06:16.773989089Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 61d85247900894606d149cf960c17d4e7283c8d9555cba554aa33fcaf8e09894
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T20:06:16.775895164Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 006daee94e0035a817f58b7758f27d62adbe709955f496421152859f5d4cbc9e
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T20:06:16.777068301Z"
    description: helm chart for multicloud grc
    digest: 96e4268874029e13b47622e1aaca475ddaab7bf59b2c458a0a6930e89b7a95d5
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T20:06:16.778631838Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: e4ade85540e845685b2ead898e38ace32d87023b32f090b955cfd40aa1ac3c58
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T20:06:16.779546825Z"
    description: Multi Cloud control plane ingress controller
    digest: 8689919b859925d01d6ce56f63613e7b2031a85d9414c58aa149723a3d86e8c2
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T20:06:16.780187481Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0dbdd60a765abab8184eb18322ddba3dc70187dd0327d29373ce50a3e50eec49
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T20:06:16.781114247Z"
    description: Helm chart to install the Multicloud Search service
    digest: b843fd11bbe98d75c910a2b13573cce1ce53240fb973a1d4d50bfac8e0d19a32
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T20:06:16.781522251Z"
    description: helm chart for multicloud topology
    digest: 88dd914e73f16cf69ce86f43ba1092fd13d50e218eab98fb9795bcd1cc620914
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-04T20:06:16.767382126Z"
