apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T13:39:10.015236876Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 220b986d314fea11fa40458278854a41f2f9e85823cd9b471f1d77b16b0e1514
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T13:39:10.018645801Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: dc4e74120cfd11c36800dd9d0163a5fa24eb1c1d2067371e0c4241c20486bcc4
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T13:39:10.020115291Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 5ff20cb19bdecb98b9baa7d1c5286bf3f2c7b871e3e977e6a1ed6d9ff63e0ddd
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-09T13:39:10.021814051Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 9a7b90637311de774c0c8d3012b4e8c55cf84f7cfdbfc268c34339dc4d0581f9
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T13:39:10.023637328Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 5f089d01aa1cdecf9fa8096547ec757c5320db91235151bfdf6f7313615d6767
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T13:39:10.024685602Z"
    description: helm chart for multicloud grc
    digest: df623e3f510881b2d58a8b5ab6d595a7de8b5bf97c5ca92702ad9c8a288114f4
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T13:39:10.025417603Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 045d2a04de63899592e9835795828948628a5fb0af4df1fc7bbd0d34220078cb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T13:39:10.026329102Z"
    description: Multi Cloud control plane ingress controller
    digest: d77b0e1d6319b466c94dc1f4355c5e1f5c56c4b0f69efb09f59d2648f168bb27
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T13:39:10.026895476Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 31a752d88cde993d0806f111bd080e03d1cbd8716bde2b25478b936fb6b9f041
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T13:39:10.02788874Z"
    description: Helm chart to install the Multicloud Search service
    digest: 5bcdcdbbcec00c1fdd80f89d1043fbf8568bf4c17e2ad04657cb96a8ed3dacba
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T13:39:10.028389975Z"
    description: helm chart for multicloud topology
    digest: a591e2929462c0c60812340b1778b6afb305044943f487b38547987cdc9de5c7
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-09T13:39:10.014648874Z"
