apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:47:51.703065899Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ccabf73ded19eb24e3769e5096c92cae99b542b411d63d944411b81bf57ce9bf
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-05T14:47:51.706344659Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: d535d99fedda44096f985e524b0f0fca9698dd6e38a2cffc0774ae6c8ce1a8e4
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-05T14:47:51.707768209Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: e162582c32acbdbde95f486e893f94d4f30221c98a60a32320e769567967fd57
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-05T14:47:51.708530607Z"
    description: A helm chart for deploying the config map watcher component.
    digest: f8f020849f019278b4c9863faca0589f147c1e7314b8724b1a9b58eb95ce12c2
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:47:51.710564938Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 03a8efae0e39862c37378eb5cbd9a7e30f81b0ad68a4c545ce53e40f06a21f2f
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:47:51.712008114Z"
    description: helm chart for multicloud grc
    digest: 18afd7f5f0f90f304358474d6cc0297405c8b6dd9ef7046796fd55c2ac841705
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-05T14:47:51.71294462Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: a3a75d3496e5a94ebede75bb6fca2d893ea8a0f9197af35a0870f8d021b63d34
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-05T14:47:51.713999778Z"
    description: Multi Cloud control plane ingress controller
    digest: 78028e201023533080ff4dbd565d5e2167eb9ab8e2c115bdeb9b30cdbaa2f6ea
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-05T14:47:51.714802708Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: a75e1e7d3d2470911b92c02244ece61393b60ca9f788179c1441f791ae4b4ce3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-05T14:47:51.7160171Z"
    description: Helm chart to install the Multicloud Search service
    digest: 3328e463c0111d4bf7652127a1fd4d6121cf77c9e575467935595abec3c87b9d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-05T14:47:51.716464058Z"
    description: helm chart for multicloud topology
    digest: df75f40d4250984265d9c5faf6a5e199bc78e96beb8c23846b6d1f23bafebd19
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-05T14:47:51.702277747Z"
