apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T13:11:00.285305427Z"
    description: Helm chart for Open Cluster Management application UI
    digest: e47ddbc60dda366e2e29a47095d53919e6b84a68aa7ddb2af1255ad5cd593418
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-11T13:11:00.288619439Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 625f8a9b8e6f40f15002a4110be9ecc1e94ec6bf27144ea6ba235c0f1e4f4f51
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-11T13:11:00.290066395Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: d386e43c330d8c67fdd30c01dd342fc0177603802232d93a4a7e22ca03463c1a
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-11T13:11:00.291818061Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 1d52ae57f2c6682b468bb89c8d5a04dafa4a6039b1defc43d42aaa54ad56bb11
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T13:11:00.293795122Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 0de890ec323f2fdd571267d63248990563a09f3d3429dc869589e51b9163ea28
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multicloudhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T13:11:00.294261629Z"
    description: helm chart for multicloud grc
    digest: 487e7b41ed9e581026482757639ca43716c3574e06c17b127f0d8d909f49c02b
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-11T13:11:00.294940084Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 6b9e50817e2a5a81d61fad9fefe3dff73633700e65a949240f9cd0de5f0779fe
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-11T13:11:00.295730684Z"
    description: Multi Cloud control plane ingress controller
    digest: edce5a7431cdbb474f4cff1597a90d5ffa247bee6107084426e7408e6bb7e177
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-11T13:11:00.297837381Z"
    description: NoSQL document-oriented database.
    digest: 0a80da04590eed4510b02528e3fa2424c533cd605583ad6c1bec226b68712be8
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multicloudhub-repo:3000/charts/multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-11T13:11:00.298463011Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0c8f25e155d39f5e53ca6ce0ef0cbb481c9aab72ae5f8824f997cb43fcc560ee
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-11T13:11:00.299393002Z"
    description: Helm chart to install the Multicloud Search service
    digest: 95c26e6c2139f3657302496eaabcd42bd1196e50fdc2a353bf8f99de7b27ab32
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-11T13:11:00.299804165Z"
    description: helm chart for multicloud topology
    digest: 81b3ec789e08102932bfb8d0173940502a910094d11deea6e6e92b5cd03ed4e6
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-11T13:11:00.284770794Z"
