apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-24T13:45:34.74766-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 50fc39f0f0acdc8bc01b4235fe034e6f44e68dc53fae5f4eadb262fbf2a55955
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-02-24T13:45:34.74937-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 6eaca422011d8ec5b986117fa6b5caed6a7acfc78e3a52006b457004b052703d
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-02-24T13:45:34.75022-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: 8ae5237c65132aa7669dd668a7295acf278a50e6d51e276a8ec592d2be7d4d09
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T13:45:34.750773-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: ef1d44b3267a2510d324b4f20c3b373dac07f65ef982399c5b096aa5767fd169
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T13:45:34.75135-05:00"
    description: helm chart for multicloud grc
    digest: efb504200ff6252b10eaea9951f2e7c1a00f28d64886702659aea5b8a557ba8d
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T13:45:34.752067-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: b0a6cb033ed664227d4be4e9a40d91d118811c3726442a0afa047e7a33f50730
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-24T13:45:34.75345-05:00"
    description: Multi Cloud control plane ingress controller
    digest: f381c6d32c13e168905601b99a6f00a1096c5c8484b5c1165433976bd5e04bcf
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  mcmapplicationui:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T13:45:34.753887-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 3c6f75b211a26b221d712dc990109222738fe7c3888591d36454189f2c086860
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: mcmapplicationui
    urls:
    - http://multicloudhub-repo:3000/charts/mcmapplicationui-1.0.0.tgz
    version: 1.0.0
  nginx:
  - apiVersion: v1
    appVersion: 1.16.1
    created: "2020-02-24T13:45:34.755181-05:00"
    description: Chart for the nginx server
    digest: dc6b9b1afd0ba0c95327c617dcece963bc70e55634943e2af5c0c2e508953d87
    home: http://www.nginx.org
    icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: nginx
    sources:
    - https://github.com/bitnami/bitnami-docker-nginx
    urls:
    - http://multicloudhub-repo:3000/charts/nginx-5.1.6.tgz
    version: 5.1.6
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-02-24T13:45:34.756179-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: fa2aa8ff87ce2fcb0bf9a6ea0117523d8b74b22f2da3865a0803d7119e3c2c46
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-02-24T13:45:34.757435-05:00"
    description: Helm chart to install the Multicloud Search service
    digest: 3f9d18672784126ebdc3d6c5de64b2c85ff110828ba4705f434f9f38a180980f
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-02-24T13:45:34.758719-05:00"
    description: helm chart for multicloud topology
    digest: 93826b6cfbc263770a60d6a4c71cb35efbc14693a06a4875c05f12dbde92ea99
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-02-24T13:45:34.742491-05:00"
