apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T17:52:20.097650962Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 29403e1f676ab8981410b2791345f11d75111273b3618e6146ab825edfa410dd
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T17:52:20.101010181Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: bca56ea757e07f6dc1205a6e57324bbf745a96eef2f4b587fa1bdb6eed9296f0
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-10T17:52:20.102435373Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 40620c3d1648f84270fbdb58780e7e34eb3473b1f913e79e0fffce675a92dd08
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-10T17:52:20.103244182Z"
    description: A helm chart for deploying the config map watcher component.
    digest: f9db41236c2e16150249540f89c1f45525ea9f2c59a056c5b58d226f73fdd754
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T17:52:20.105248079Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 4560e8cd35a45f6dd4a178ae50f15447e8ed69487c1ef3d0590c80e41d9ffb5a
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T17:52:20.106559201Z"
    description: helm chart for multicloud grc
    digest: 77293e3a47b478ab0bfe9e730a534fba8a23c6d364d77f0ab09e36a1aa89e7bd
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T17:52:20.108088503Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 9efffaddab1ff71a99857eb0a032b9b522fb7837158cf9a26504205427e34104
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T17:52:20.10896395Z"
    description: Multi Cloud control plane ingress controller
    digest: b31a88e04bdec4f7e2e762c0ba469b7e27b4326730426a0ec049947bae2caf0b
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - apiVersion: v1
    appVersion: 4.0.12
    created: "2020-03-10T17:52:20.111097131Z"
    description: NoSQL document-oriented database.
    digest: 6e3911cabb5285018cf51e98c234f2fcf680291d8f2f7f1e2876842f8dbdd230
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-10T17:52:20.11168383Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 7dbf82d32b3465883a4ba6c3a48768ed435f975bf258b8370838a5ad2745d30d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-10T17:52:20.112613558Z"
    description: Helm chart to install the Multicloud Search service
    digest: b8676b41cbb483b20dce0190dc5504006fa89ff3ef2f233f5e60c9cf04a79a8e
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-10T17:52:20.113057919Z"
    description: helm chart for multicloud topology
    digest: f4e47bcc21bfe99cd7217a79ded2de78c97a6cb8b43976004599ab16ad1208c6
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-10T17:52:20.09665862Z"
