apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T22:47:24.801477955Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5357c1ed89dbdb75dde168519f1068eebf2007660c6c0de0df41e90bdb5586fc
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T22:47:24.804700105Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: a547d7bcf988054e2bd2314a70c70ef95cfc02850768d40be6e0997afe54cd08
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-09T22:47:24.806054776Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: edb72a3636d1741aa60f795d644a4736f1faae00420f4ac7833365766b25b967
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-09T22:47:24.80762756Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 6b5c867517b874d2cffe4814f25ee2e52386215fb360e5fe9497c2a0f9d7f7dd
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T22:47:24.809441244Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: f5d1800dc2d5681c74d206ab2d38d926e6c60289db83da1a20b44c01b231a9d8
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T22:47:24.81046076Z"
    description: helm chart for multicloud grc
    digest: 5ef6f7706eee7d5c206b30c4ba3e5ba66932e35d0d9f98cf128333511451ae0e
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T22:47:24.811168669Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 240bee9b3c827e5c061dd47ca735cea86288929e1f2e99c0a2d10a2ba0fdf004
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T22:47:24.812002158Z"
    description: Multi Cloud control plane ingress controller
    digest: aa1098796fd895867d535734d622f4677864357eff4eacb8d6fd4fd1ce6702ce
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-09T22:47:24.812590963Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 37f291001ec1a2b632d0f6edbfb89b6ab1794c34205abf74d6df561a7eca372f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-09T22:47:24.813496268Z"
    description: Helm chart to install the Multicloud Search service
    digest: b80e555e60732179e26c950cd75f59f3b1f9afcba78be8385e2da7cd0c404516
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-09T22:47:24.813950036Z"
    description: helm chart for multicloud topology
    digest: d31ca80da1f9da77c27f56ba080dc77ddf24571bdcef4dbd1ebed819d8c9463e
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-09T22:47:24.800916577Z"
