apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T07:49:44.757917-05:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 080d61b4d3c8d3ba9f1b03a975acbdd083c1668c2d610045583ca4dbeafadcb0
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multicloudhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-03T07:49:44.762275-05:00"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: f0d831821a4c8b769256b36a168d7c6d7e5101a5c6ffe9e97df214891cb18671
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-03T07:49:44.763807-05:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: f517eaaffb588d6f9b0cc95ae94876011f963c5e3722308c3f255a5a4225149b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multicloudhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-03T07:49:44.764818-05:00"
    description: A helm chart for deploying the config map watcher component.
    digest: ee1447efae2df30c44cd83b67cb2a7cff7e9081b3f67e40ef1bf154f7aa95b84
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multicloudhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T07:49:44.765473-05:00"
    description: Helm chart for Open Cluster Management console UI
    digest: 7762f0a7e7b7d37e2ac94ca13d2b786f97fb9100befb9eccbe7aa485a20636af
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console
    urls:
    - http://multicloudhub-repo:3000/charts/console-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T07:49:44.766123-05:00"
    description: helm chart for multicloud grc
    digest: dbd3e0ed6acf43e28162acffa7088f6c0f62febe95d424e273d0c283ee6a2789
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multicloudhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-03T07:49:44.76699-05:00"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 85f08a4c46d51e726cac32ca81b4b0e5665b2d0c635a16a2c17a392b7d72cf92
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multicloudhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-03T07:49:44.767997-05:00"
    description: Multi Cloud control plane ingress controller
    digest: f9491b47d4fa5579fe64e3ab17e6c0627c94de3b85f952fe7054564cfeaae7c9
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multicloudhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-03T07:49:44.768666-05:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: e438d3b61ea1a42668b5dc7dcb36c04c94f375b217a65abd261efac98f7b5beb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multicloudhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-03T07:49:44.77048-05:00"
    description: Helm chart to install the Multicloud Search service
    digest: a5f28cf1346a780a88a1c73580b1d83be77169c79d9b4095ae6b943691231e11
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multicloudhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-03T07:49:44.771133-05:00"
    description: helm chart for multicloud topology
    digest: 7ce7dd11d63689bd3a169a9b4ecc0db03c7b3d4e227c3d7aad8700116c238015
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multicloudhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-03T07:49:44.757115-05:00"
