apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:08:42.84197965Z"
    description: Helm chart for Open Cluster Management application UI
    digest: f582dfdcfc516e395008a15775cb85bd3ed8269d1e2d9b764d7a1f24d170031c
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T19:08:42.845257872Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: a1bf3401c9a38d87abf5e9dd879f5d5fa5def3cd77dd3616ecc54c95686fa0b9
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T19:08:42.846703763Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: b9237205ebb65766f4b65040d924423044f7f7a2c0286231bab8b1abc925b694
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-04T19:08:42.847483444Z"
    description: A helm chart for deploying the config map watcher component.
    digest: d865327a7b7f8d0c7040727de0937b995c8e11c1337380d5d63d9870b8ec91da
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:08:42.849284847Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: a63723f17be6f9df9a1b81525078539fb2aeeb8a04c9156aead0960532962ddc
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T19:08:42.850453439Z"
    description: helm chart for multicloud grc
    digest: fd34cd9bbcf9c5f04b6127da2c27f972f4db037297cc74b052b90bdd52c9628c
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T19:08:42.852234255Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 098d5c66ca8ce5752ddafa86f5e98bff5effb61420d01e811383c40b901f6ee5
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T19:08:42.853188964Z"
    description: Multi Cloud control plane ingress controller
    digest: 79d0d5be7d20b8e1abd2a83b284d64531de88d3bd94a7c0217da9f5ec9062190
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T19:08:42.853849079Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 6f61f26226fa87f19e230387290c500bdf6aae4d36f91b5744503dce43521ce0
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T19:08:42.854839817Z"
    description: Helm chart to install the Multicloud Search service
    digest: dceba18973f4f507378b0078b85c919e7f652118f76375314a908d46acc4c4e4
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
generated: "2020-03-04T19:08:42.840791375Z"
