apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T16:57:39.393204079Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ec4db9b158cb2e65c539dc4b2b5c96e5cf2fd5e65672322dd007b05545453184
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T16:57:39.396552142Z"
    dependencies:
    - alias: crd
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 65a2a18502ecd9d74e6bb0b38ecf32cc6e97c7fb88e62af7f767471a975ee770
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-04T16:57:39.398014391Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: eefb47a34c3d13f0faceca91bc66eb6f28e9dec697a5d841243070a1a7201a7c
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-04T16:57:39.398827774Z"
    description: A helm chart for deploying the config map watcher component.
    digest: e3f21a9262721e348fcb87e03918b8e47754c0b6ed446e99cb04e81da230af37
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T16:57:39.400528379Z"
    description: Helm chart for Open Cluster Management console UI
    digest: 502e7cc470d0c288ef00e01f22d8e9f5056fb69b3d47270ba99eaa660468a5cf
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-04T16:57:39.401875346Z"
    description: helm chart for multicloud grc
    digest: 6e2e50d03200207234f41ef827732ef77bd8c6a126960f09e6d6e90ae9f321e3
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T16:57:39.403225697Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 026e29d0f8dbfafdc8cbe1dc835ed2b710a97128432bd411a5396e4f71e06841
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T16:57:39.404061638Z"
    description: Multi Cloud control plane ingress controller
    digest: 3345f543ac847c0b51d2c3e7d477367035ce0a16a147e4ffef293620ae5dcdd3
    keywords:
    - ICP
    - ingress
    - nginx
    - IcpClusterResource
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-04T16:57:39.404626866Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: cf5eaad2a9fb53db5006a87e907f10995b760e5bed90380395ef41243aa06ee6
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-04T16:57:39.405598836Z"
    description: Helm chart to install the Multicloud Search service
    digest: 745e6599ac9cc32332572f90f0af416851b4b517a5977b7db2e612bfb03ccaf8
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - search-prod-3.5.0.tgz
    version: 3.5.0
generated: "2020-03-04T16:57:39.392279866Z"
