apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-26T13:55:49.465560875Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 7ca134e304f0f8f11d8c45c5d6da4850ae336fe2cf618dc09771c75f605273de
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.2.tgz
    version: 2.2.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-26T13:55:49.466588362Z"
    description: Service for issuing and managing certificates.
    digest: 3ce1753cd63067578672d581ef7c2cbb64cd092f329d63755f5982e9cfa93cd2
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.2.tgz
    version: 2.2.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-26T13:55:49.467957308Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 11e457bc887bcdc664306704b551db3bdc3da8727d154cb18f9ba5490b2d8e63
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.2.tgz
    version: 2.2.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-26T13:55:49.468622657Z"
    description: A helm chart for deploying the config map watcher component.
    digest: a760ede1240ed2df3b38f7115671ff52b2ef96ca3638b7bf9431e11bd10a12cd
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.2.tgz
    version: 2.2.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-26T13:55:49.469330143Z"
    description: Helm chart for Open Cluster Management Console
    digest: 8116981952d55ebb3b083339059f13f6399b51e5de776fc0907e592c44284776
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.2.tgz
    version: 2.2.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-26T13:55:49.46972606Z"
    description: helm chart for multicloud grc
    digest: 43cc3f0f854d698debc0b30d3a7ba6f66d45e3fae0684976b26a9f41fb7a75e9
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.2.tgz
    version: 2.2.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-26T13:55:49.470508215Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: fb47f17b1c60b412c3794f15ea73fe56aea149371bc11650e269d50895bf1895
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.2.tgz
    version: 2.2.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-26T13:55:49.471517033Z"
    description: Multi Cloud control plane ingress controller
    digest: 253dbe1a90082d59bc1df48485e00b15deed11fbb74a3e4f8dcdcb845676b279
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.2.tgz
    version: 2.2.2
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-26T13:55:49.47237151Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 4eec603f27864451fad30922d93bba922365583e728a281373bf3eb300f0ac86
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.2.tgz
    version: 2.2.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-26T13:55:49.473807544Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 060b0f02b707126ef47936dfa43734e4e63888002e791e3878d09ff837032af5
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.2.tgz
    version: 2.2.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-26T13:55:49.474800491Z"
    description: helm chart for multicloud topology
    digest: 5f071d16725813c647bd2e954412413dde84e3890f703bb5fcd716ea56a6a289
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.2.tgz
    version: 2.2.2
generated: "2021-03-26T13:55:49.464916042Z"
