apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-11-09T13:46:55.362100666Z"
    description: Helm chart for Open Cluster Management application UI
    digest: b045757e19d82fa5f555e06f849c49697698a4964b6dcaedde1a209948f830ad
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.1.tgz
    version: 2.1.1
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-11-09T13:46:55.365337844Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 223ce24c3bca0fa1eaf064bdf99f57979ed2c2915786e5162408eff3afb7a033
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.1.tgz
    version: 2.1.1
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-11-09T13:46:55.368248248Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: ffe6542328d19c9fc95f96d8ac1cefb03cbef18f0f9712801cb1f3d91dbdb225
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.1.tgz
    version: 2.1.1
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-11-09T13:46:55.36992617Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 845be8d6e651852595e19acd6a8a18b735217a5511cab72e95588b67eb374f0f
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.1.tgz
    version: 2.1.1
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-11-09T13:46:55.371172716Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 7f3aaad969fc6f750514bbd507e5ac77bce3f5d97581bb9e5e6b025d1a9dd86a
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.1.tgz
    version: 2.1.1
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-11-09T13:46:55.371765377Z"
    description: helm chart for multicloud grc
    digest: fd02e902399ac7c27f7c85c73ad3407ba3694b1a7b38694358a9cd4f64a7e87c
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.1.tgz
    version: 2.1.1
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-11-09T13:46:55.372573916Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 32583cf4bd81a2585a82f7a86b2c5dfccb511c58d5c5c191c36da9fb2ee692cd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.1.tgz
    version: 2.1.1
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-11-09T13:46:55.373521795Z"
    description: Multi Cloud control plane ingress controller
    digest: e67327e01971236867aa5131d38ca0e220d4521ceaeedf010152b3db47cc6cc6
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.1.tgz
    version: 2.1.1
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-11-09T13:46:55.37435228Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 550d5d9aa469518d111a6b28614288a4f163211511e8a48c32c18929dcff0448
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.1.tgz
    version: 2.1.1
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-11-09T13:46:55.375338076Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 5134958b982828478f7af8328853417afb77c0d8134644b95d96eaf412fec1ee
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.1.tgz
    version: 2.1.1
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-11-09T13:46:55.37575297Z"
    description: helm chart for multicloud topology
    digest: d53ac87c7876899ac2afd88d3fe921b4041680624a252028dad9c3543e4b02fd
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.1.tgz
    version: 2.1.1
generated: "2020-11-09T13:46:55.361422352Z"
