apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-15T22:06:54.176203396Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 1acda7a20f4fe089a1f1987c826373d022b77786876473d07eb57aef723a1e6c
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-15T22:06:54.179587387Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 3d14265a51298bfd8c8100459caa7f18c6d3250a5f370655c70b12a1bf3ca41a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-15T22:06:54.181144119Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 1c4e1c67f027369cbe3c378e529a0c2df1cf7f7f9c1d1c59e242032c804a4786
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-06-15T22:06:54.181991281Z"
    description: A helm chart for deploying the config map watcher component.
    digest: fa9c5bb1ec8a03ca079c2c125970b565f841b0bea581b4f951831d8bcac48045
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-06-15T22:06:54.184283663Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 1296a5b652f74889dd149efa816e69b8912da0f114a00def8d834eea3f0e3ca7
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-15T22:06:54.185595133Z"
    description: helm chart for multicloud grc
    digest: e0ba4f7114e408a0bc21b27d61159dfc1c060a78120ff0d5be3d99db984e6100
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-15T22:06:54.187209735Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: b0e8bc15005f413e793c6e22fd1c18b57c48c32d50572573bc37875ff5dbc8f2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-15T22:06:54.188267008Z"
    description: Multi Cloud control plane ingress controller
    digest: 2fb01515b2631eb188ddc09193cf1d90706a7b031006935dcf9475139397c011
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-06-15T22:06:54.190594446Z"
    description: NoSQL document-oriented database.
    digest: 1a83ffb94a51537aa241993532d31f0dfcceeda8e6d94abbc4827a80482ac972
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-15T22:06:54.191558785Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 971aeba442576d1b4ca634a0bd333cac7913359d4b4dc690c34408887303cf26
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-06-15T22:06:54.191160429Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 3c2a7f4db02a43fd003dcbfd7861d50535aef15811f6228883c5c175507d254b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-15T22:06:54.192517855Z"
    description: Helm chart to install the Multicloud Search service
    digest: 81fb7aa63c863df53c004b652ccefa381d0c42c800298a0ebb327045caabd2ed
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-15T22:06:54.193028305Z"
    description: helm chart for multicloud topology
    digest: a33020e54aa063a7de1483e58417d41f84a7018d307ed671c3ec7bd37e19562a
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-06-15T22:06:54.17491296Z"
