apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-11T21:23:23.945652531Z"
    description: Helm chart for Open Cluster Management application UI
    digest: c1a5a900ed74bb4bb346de561397cb3638b5b6885a561db7ca034ae506ae3741
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.2.tgz
    version: 2.2.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-11T21:23:23.94667739Z"
    description: Service for issuing and managing certificates.
    digest: 9a98b26306e75d93b6d5123157d51532fbf9159ef642f7ce4b326258b0cb8701
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.2.tgz
    version: 2.2.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-11T21:23:23.948040103Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 694b1467f69edc2c87389ebc701f3fb745964b8926f91661142d9d4226826551
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.2.tgz
    version: 2.2.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-11T21:23:23.948811362Z"
    description: A helm chart for deploying the config map watcher component.
    digest: e2d1184a3d09dfdfc78369659f2d01867fa85c8d76350f1f1f90d1d813ef321a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.2.tgz
    version: 2.2.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-11T21:23:23.949466078Z"
    description: Helm chart for Open Cluster Management Console
    digest: cc53d313d1c5cf2ea001012e3db8eb20476eeb6518ccfad7a5231bcc4da11564
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.2.tgz
    version: 2.2.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-11T21:23:23.949860563Z"
    description: helm chart for multicloud grc
    digest: 2a8f72f1af24eb4ab116abc6a39f70846d01940b47772d2249df308d4291b245
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.2.tgz
    version: 2.2.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-11T21:23:23.950689405Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 0f7f989eb91dee41cef4214a12f8bcafc91cf2ea2e30d77f50f8d43e5e4f3782
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.2.tgz
    version: 2.2.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-11T21:23:23.951736592Z"
    description: Multi Cloud control plane ingress controller
    digest: 46c066e66ddd3eb921998c75108225d2d8b47c32ea2687f46a4d6f7fe1ee6d6b
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.2.tgz
    version: 2.2.2
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-03-11T21:23:23.95301331Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: f7667fb8291a4d669c0a993f00d0f137465b3d7879e4ff01c165c1d91dc21306
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.2.tgz
    version: 2.2.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-03-11T21:23:23.956003377Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 54340c36d6799a570ecd7a2c8ca52559696ed424753f7c6d538434ca3a403db1
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.2.tgz
    version: 2.2.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-11T21:23:23.957004484Z"
    description: helm chart for multicloud topology
    digest: eb24d278c49ddab4e57ab78411776c485471e0ba1f43898d32cb33c22726d6ae
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.2.tgz
    version: 2.2.2
generated: "2021-03-11T21:23:23.944980771Z"
