apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-02T13:13:06.696791957Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 27f5df74e16971a3904c92664948a54cfb311fb72d60b27e746fb90f3620606f
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-09-02T13:13:06.700396697Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: be3c6492246864aee8f1be43721b3f0b286746b95cc1503b4ebf695e933a2584
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.1.tgz
    version: 3.6.1
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-09-02T13:13:06.701892442Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: b0b7d1a6952185d95797c63949dd1e52fc7f739601003be4dd4692132302c93d
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.1.tgz
    version: 3.6.1
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-09-02T13:13:06.702830293Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 08869f4df160232c0340e47994de6c4aa7b90b6df8918e2b0af39aad812733a1
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-09-02T13:13:06.704905305Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 33f3ecfcee502d92cde800baa22ab892debbf35254bd2dff79ecec6072854751
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-02T13:13:06.706022366Z"
    description: helm chart for multicloud grc
    digest: 9627ded6154878139fc8e586bdff1159836dc02847f487dba1ec99acf6c47f89
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-09-02T13:13:06.707898885Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 7b8056a12ab1d67bfcf2bacf902b8b9bce17a1caa40d117dfb880ace81429dfd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-02T13:13:06.708930754Z"
    description: Multi Cloud control plane ingress controller
    digest: 12aca1fc358abe3f2aa5191cdfb42cd4b6e39265c54a691b2d539f8f9e45fcec
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-09-02T13:13:06.709697557Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: f77de68dd30acb077dbb72397f512eb373cc4d2b7d30790de35a9890c556dec9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.2.tgz
    version: 2.0.2
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-02T13:13:06.710712159Z"
    description: Helm chart to install the Multicloud Search service
    digest: 6cfaf912c8af902fa435feb9f7b9f663afe9e949ec9c34e2ec879e6d4f29a933
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-02T13:13:06.71109832Z"
    description: helm chart for multicloud topology
    digest: 92a6bafbc97ecc2e0b0ea8af4dfc78b70ff8ca3a522a60f7c23c92a16bc1d10a
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-09-02T13:13:06.694884704Z"
