apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-04-27T13:00:02.120769-04:00"
    description: Helm chart for Open Cluster Management application UI
    digest: 2b217b2ed4224b35a81aa19e96d95f30df782c77e83d1952a1d4bda7ff886bbc
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.7.tgz
    version: 2.1.7
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-04-27T13:00:02.123531-04:00"
    description: Service for issuing and managing certificates.
    digest: 7aa0557632890645927fca9e2fe1046395bd61eb2f4582f8d72e4ad8651312bc
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.7.tgz
    version: 2.1.7
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-04-27T13:00:02.125235-04:00"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: e0ce89cf332b8adf3cf4cffaeed62155404b0254f6da60d0ec23d3a8186ab145
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.7.tgz
    version: 2.1.7
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-04-27T13:00:02.126221-04:00"
    description: A helm chart for deploying the config map watcher component.
    digest: 353e0db3c41f75d2f19492fa272840fc5cc622b1a66fdc753de0a6e82c835037
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.7.tgz
    version: 2.1.7
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-04-27T13:00:02.127091-04:00"
    description: Helm chart for Open Cluster Management console UI
    digest: 7d4f72ecfd60215452d5bdf76ae8af22ab3bacbed2eef0793219e3cd858b799c
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.7.tgz
    version: 2.1.7
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-04-27T13:00:02.127782-04:00"
    description: helm chart for multicloud grc
    digest: 222685bec441934db5b65eae197a588b27bfac73a91195f94b46c2f319287159
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.7.tgz
    version: 2.1.7
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-04-27T13:00:02.128753-04:00"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 1d1e0eabb7dfb1a39f9a4ad18040a80569e9e072f90507105dfa903ea35f0741
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.7.tgz
    version: 2.1.7
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-04-27T13:00:02.129943-04:00"
    description: Multi Cloud control plane ingress controller
    digest: b702be3c6b382dcaf5e7dac090e7df4297c951346544e18f2689b8d1d6783ec2
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.7.tgz
    version: 2.1.7
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-04-27T13:00:02.130822-04:00"
    description: A helm chart for deploying the cluster lifecycle
    digest: 548cb803803a8e0f320066cdd51386ce0abccb6dd9b3374e6555db2804441c06
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.7.tgz
    version: 2.1.7
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-04-27T13:00:02.132589-04:00"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 617e3f0fc19a8986d1f7e39f6db98a37104209a382ee6a6e2a15ba25db7ec228
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.7.tgz
    version: 2.1.7
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-04-27T13:00:02.133175-04:00"
    description: helm chart for multicloud topology
    digest: 97df2c43edd9fc145bba06dd05a824acc5e2a590007a1e03c35b1221f85dbbbe
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.7.tgz
    version: 2.1.7
generated: "2021-04-27T13:00:02.11976-04:00"
