apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-04T18:32:42.505093356Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9ece8f695234719f0e608344839630a16cdfb7ff0c7b950266841d0237a4e435
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-04T18:32:42.50876852Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 2a3392d6f081004eb93acd2123d3f1c3d9dd47b48e56da606e95ac84adab66a5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-04T18:32:42.510319222Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 52ef073fc2b8f3e2c2cdd43d6bf890610b8014a57961c9a0159a6709407c420e
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-08-04T18:32:42.51124219Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 977be0ffa908f6a1a4f711099ae3dc9b27c0c757c68bbb2afe0c8c6ddcb4aa4e
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-04T18:32:42.512152436Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: ae1effee6245f252a6c9bf02f40998a153ac70186cf43679a37b81c64865c853
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-04T18:32:42.513654133Z"
    description: helm chart for multicloud grc
    digest: 119577549886ffa16583bfaa40cfac09afa781d64bec955db7a67f76f8295753
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-04T18:32:42.515423277Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 0f5137490ac5a7cd5f01b916dfa03eb3fa9adef45793b6feea793e940f14bc98
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-04T18:32:42.517020334Z"
    description: Multi Cloud control plane ingress controller
    digest: f9806f3d20b297187d6ee1457867f02cb4010358dc93c430d220ce165f7596d5
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-08-04T18:32:42.518775086Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 8089089c575bc4319038fde854fc1fc5abf0e446654b67aca2bd90285983b86b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-04T18:32:42.517924509Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2727c2a51580ccea028ae5d2e037f14c21624f9720e581b6522723a5479b55e2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-04T18:32:42.519869158Z"
    description: Helm chart to install the Multicloud Search service
    digest: ec1a7245591cff69dfc43fb70900ae8950bbd0c3f4f9be5c2572d15c3a5cafc8
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-04T18:32:42.52030997Z"
    description: helm chart for multicloud topology
    digest: 5da1756e2dca0be322d482b24889765954a643fa37473fa10ce8de0f8be8c26c
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-08-04T18:32:42.503493359Z"
