apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-06T19:59:17.517208593Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5fe09a99af8db00579afb2e049c6eed608d628382dd57b48bd6be03b98560bbf
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.2.tgz
    version: 2.1.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-06T19:59:17.519898549Z"
    description: Service for issuing and managing certificates.
    digest: 6909a2703f07aee6b7b1efe0ca2dcf2ef76075af0deb7c39459184e276c502b9
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.2.tgz
    version: 2.1.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-06T19:59:17.522057653Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 66fe4685b83a08e5fb2cc3ed3983be710763d61f2168fcca71c4b777d07576bf
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.2.tgz
    version: 2.1.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-06T19:59:17.523766828Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 3a142ba664ce1b11fa59fba8fbdf31dd2174bfdc7c1338db83ff46066ec9e20a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.2.tgz
    version: 2.1.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-06T19:59:17.52521918Z"
    description: Helm chart for Open Cluster Management console UI
    digest: d2c518777a34dd7e50f2d188ef784527897fb75e3fa5ef24fa00360b686197d1
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.2.tgz
    version: 2.1.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-06T19:59:17.525718568Z"
    description: helm chart for multicloud grc
    digest: ed8b670bd9e66da854fbbfaac251ac63415118f9dc7cc910afc813bbc819fe29
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.2.tgz
    version: 2.1.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-06T19:59:17.526518674Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 69089f573fa83cdddfa132f58c1dfbe020c8607673e3d95d67c220d2c0c3da5d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.2.tgz
    version: 2.1.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-06T19:59:17.52745962Z"
    description: Multi Cloud control plane ingress controller
    digest: ee138b5e596998e3994991e5db65ab2e50d1bbce37869d58a235870f4338f027
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.2.tgz
    version: 2.1.2
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-01-06T19:59:17.528283928Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c04ed7153c5976a8fb15a5c023d34850a95c9dcb1d27e3432c4b36f473ea72d7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.2.tgz
    version: 2.1.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-06T19:59:17.529245787Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 8ae1e13a6adae8547c1f358f7b8804d98f476cd90b8bdd1ab8f3dcdb961b65a4
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.2.tgz
    version: 2.1.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-06T19:59:17.529610996Z"
    description: helm chart for multicloud topology
    digest: f9330b7bd3eb08ec5743a2514808a3614fb903528c8ffb10b93f340eab934377
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.2.tgz
    version: 2.1.2
generated: "2021-01-06T19:59:17.516605058Z"
