apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-01T15:27:10.725058643Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 6b9e12cc0ca4fa97a821a580aacadd93602d82e8c94dd7b92bd26ee60d81c073
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-09-01T15:27:10.728874651Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 6e41063c7ac937d24cd4b57c3bad003bbccf476d8ed5bf4e80886d3b118ffd6e
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-09-01T15:27:10.730350032Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 8246a34c33e5ba03245b727eaa3f2d87c79125e87d64731ef018bfe7a4cbc41f
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-09-01T15:27:10.731182606Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 4c1e180e02f214469085ad3f0636e24a97d13430a0d80d256e299864a1902295
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-09-01T15:27:10.732103931Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: ded4ff2efa598885179ccaff9daa45e263063a4208bffa2f1b3d6a5212c75819
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-01T15:27:10.733498198Z"
    description: helm chart for multicloud grc
    digest: 0741d352d49aad9cfb94c48a518b1d6e4198a03d012436cd66bf3efc5be089e3
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-09-01T15:27:10.735206227Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 8431a7d7fd4a12ce60f7cbf5efd27b238be1ba9f8efa65cc93d930db7afad6bc
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-01T15:27:10.737066432Z"
    description: Multi Cloud control plane ingress controller
    digest: fc1073320c0755b4ef07a05e8a0ae732d29d5a41212e4044aaeae5af00dc2d66
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-09-01T15:27:10.737907505Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2671771a413310ecc5ab167a6b052f5ffad5887b18796e0268c200e3525224c7
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.2.tgz
    version: 2.0.2
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-01T15:27:10.738992505Z"
    description: Helm chart to install the Multicloud Search service
    digest: db8f94cd6ab561e2559eadd9086d4989f56a7a50498c9d371f3a5b79c8fe28d6
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-01T15:27:10.739386268Z"
    description: helm chart for multicloud topology
    digest: d01928e9fd01ab64e6709e687e9672a8d7fd8e86b454df3cb9e3490dd983d9df
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-09-01T15:27:10.723421642Z"
