apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-05-14T13:38:53.082789081Z"
    description: Helm chart for Open Cluster Management application UI
    digest: da514a108e929b6355bed0ef8ec18469f73be461d1220a72d841d0d8b65f0117
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-05-14T13:38:53.086585999Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 0f403a9181ec3a8be00dc27deea1e749aba1b7f56dc236ecb144706c83669179
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-05-14T13:38:53.08919644Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 197545774925dde192a9295786f9f0c87586db7d178c8cad12f296076bc3c15b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-05-14T13:38:53.087872376Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 4b40eda95507a1851bbe8269a0c8ebc4c0b5c19efaaaad3eeb7f2f2a7b17e380
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-05-14T13:38:53.089924094Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 570ae9eacf0393bfab7dfa2f264b49bc3c5d53aac00a5d6a4d65bff1c35970b3
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-05-14T13:38:53.090815963Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 30656d1365cb8dacb19fcd75bdeba45e691d98960849d6065d4f4197bef0c78f
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-05-14T13:38:53.091266125Z"
    description: helm chart for multicloud grc
    digest: aaf90ec5312820be9fdc01c95a67b61edfd93aa3e4ed82f505cca95faef446c8
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-05-14T13:38:53.092748574Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 3957d43053a65b0b4d09ad1b3b7531b374aa4b149e63251c9dcc5b421d1a6efd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-05-14T13:38:53.092003965Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: dc7382d21e70a29198eb3cba723f4b6bffccc6f10e46132d6821ea6feeba9e02
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-05-14T13:38:53.093713829Z"
    description: Multi Cloud control plane ingress controller
    digest: 9f340251d7d7843207a28200127b51d7fdc4c767f5f9b473f39a2b63f55c0f4a
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-05-14T13:38:53.096867262Z"
    description: NoSQL document-oriented database.
    digest: 603bac3572d23c671df0bb69efd62010ec1f29e47ce730dc970a3dcf5eaa3d7e
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-05-14T13:38:53.097816971Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 147ad4bfc6730a24e4cc394f6d4b0e5825bac0471002683654bb5b3b5a67d920
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-05-14T13:38:53.099702775Z"
    description: Helm chart to install the Multicloud Search service
    digest: 70b1e87a4cf8108aa1eb9b873dd4ed59b4b10dbf685fc55c4d8943b29fc0f877
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-05-14T13:38:53.100537538Z"
    description: helm chart for multicloud topology
    digest: d99db79dc0716b7767218e2a7342ac2677d80ed6add49191cfae03406dd2be95
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-05-14T13:38:53.081628891Z"
