apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-15T17:46:09.388790544Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 910e260f5f951c856370cebe38306ed11ae0c25d3ff474b74ee30642b06bcfcb
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.5.tgz
    version: 2.1.5
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-15T17:46:09.389783544Z"
    description: Service for issuing and managing certificates.
    digest: 7f69cf059ed63248fb606409f04bc938e76b21215e9d9f03476ad58385278a6a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.5.tgz
    version: 2.1.5
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-03-15T17:46:09.392628707Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: caca4d6e4d5ea1855480598bd0f914ba9eb94b11e16b5bb4230cc5778fd58021
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.5.tgz
    version: 2.1.5
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-03-15T17:46:09.394322047Z"
    description: A helm chart for deploying the config map watcher component.
    digest: a95435ec0151e33033e472a13c8a8d8885274ae6f56f55791272aabb0ea197d1
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.5.tgz
    version: 2.1.5
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-15T17:46:09.395009322Z"
    description: Helm chart for Open Cluster Management console UI
    digest: e20e4a6cc6166f97b5d5fa9663b60194ff0cb089254ed287268300ea2e1bcba3
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.5.tgz
    version: 2.1.5
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-15T17:46:09.395425415Z"
    description: helm chart for multicloud grc
    digest: c2736efc0e80403de033d197e4908d39421357cb151651a1b1536bf40bf61fbf
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.5.tgz
    version: 2.1.5
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-15T17:46:09.396167874Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: e905442c4467bb54f287b9cbaf86a72880139511abc2174c1a88dfb0d91e1e51
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.5.tgz
    version: 2.1.5
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-15T17:46:09.397115037Z"
    description: Multi Cloud control plane ingress controller
    digest: 0c365ff67f514130bcd0ef1daafb9a26e63094ebd5a541d4177ab7c80ac17b38
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.5.tgz
    version: 2.1.5
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-03-15T17:46:09.397836642Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 98885e2c8cc3f0a9c9bca799f42c245de9633ff877ae828a9bc2fa3d013c40d5
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.5.tgz
    version: 2.1.5
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-03-15T17:46:09.398858977Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: fa136421253fe2732550058effa985177325914dfcf558f61de58f3d54687400
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.5.tgz
    version: 2.1.5
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-15T17:46:09.399294263Z"
    description: helm chart for multicloud topology
    digest: 15f9f9aa3c3d2eb9c82369d57f9429fe708aa69f854aee2e41cc60f67c5d9932
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.5.tgz
    version: 2.1.5
generated: "2021-03-15T17:46:09.388190513Z"
