apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-15T18:46:32.656884061Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 3550d994457f8986a411b7ab512a6a58aee2550d593da2c40a7590a43469f22a
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2021-03-15T18:46:32.660050939Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: c6ecc55a4b248ab7a97f2ded7de639fa1961ec0e0918c8eeb6216e05f5657c91
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.1.tgz
    version: 3.6.1
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2021-03-15T18:46:32.661458682Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 94783726f0eb02736ffca105bf28465d2df895dc1da98b25e9ae24192572a654
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.1.tgz
    version: 3.6.1
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2021-03-15T18:46:32.663260266Z"
    description: A helm chart for deploying the config map watcher component.
    digest: c02c5bd7c1054a3d67fe52bf5fa5bd9e555b5078e098f401fe3e3d16dd4f1f21
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-03-15T18:46:32.664949474Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 14a0d4d6ca3a48167b0d46c21fe5a1afade504c85c9d5028ac403eff2764306e
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-15T18:46:32.666072846Z"
    description: helm chart for multicloud grc
    digest: acce71ea90fa3defa7da7530963a0874626d0239c3e0081b4a6ac20dc11c1f3e
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-03-15T18:46:32.666955954Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 64770fc5ff29e1e358a6f9bd2b57c197eeed83ddc1b07be1f6fcde978d3be6e3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-03-15T18:46:32.667922256Z"
    description: Multi Cloud control plane ingress controller
    digest: adb899cc9f9a56ad1019b480775f35b2d917004506a7b11bf84039d922f0d3c7
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2021-03-15T18:46:32.668749753Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 0a23825e7c825ee7973490646d1d4f157e7b4ae4afb10cd5920fbba98a2814ab
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.2.tgz
    version: 2.0.2
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.1
    created: "2021-03-15T18:46:32.669743248Z"
    description: Helm chart to install the Multicloud Search service
    digest: d8b0bc82914e324b6ddbe9d41a0a99d99f2680d0443afdebf3cc9aa98d789e50
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.1.tgz
    version: 3.5.1
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-03-15T18:46:32.670226979Z"
    description: helm chart for multicloud topology
    digest: dbb6cbf4d2ae9527722f04c36863bccef2c71898420131e37d41594d27c511b5
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2021-03-15T18:46:32.656157772Z"
