apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:40:12.491068577Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 6bf3fb8b424c26e5ee90f90184abb1fd2e68669b83218143d44d3c8e1292203b
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-31T18:40:12.494495145Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 0a0f4e00621482390c9e089d6bc4938cf4c0f3f2d623366bc36b15139a90ef90
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-31T18:40:12.496041047Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 02ab89e06cf775adb78629553c0ee69337fada3cfeda01fc2090d6b004b14f2b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-07-31T18:40:12.496899557Z"
    description: A helm chart for deploying the config map watcher component.
    digest: fc539bd59e28ce6fb2640e62394c6698de6eb1b5f11cfc9e0f7a85bf2deee752
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-07-31T18:40:12.499293051Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 42065304302cfdff0090d821d59dd9741c252eb9f59050a0ac63f0f08a1dffef
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:40:12.500592533Z"
    description: helm chart for multicloud grc
    digest: ab39a37a3fbc91ccd50533da291c727bf393e237347c7f529f00740a707bf196
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-31T18:40:12.501455467Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: d7906358028b91a5bd996ae65f17f4f5fc23b38a59188fb3c694fcbdcd9b9008
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-31T18:40:12.502634963Z"
    description: Multi Cloud control plane ingress controller
    digest: 4a61040da0ef582c5bb6ada433f92a548f7d8451e90066cd46c9fda39ae078f6
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-07-31T18:40:12.504371197Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 3c1a4048676955e7bd105e579fd035347f30e8232eeb3b849ac32c125e202a35
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-07-31T18:40:12.503433152Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c39e5b3c2669aaed3c47dd86420abec625faa3a81fe0508b4a26aafa4d350082
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-31T18:40:12.505456408Z"
    description: Helm chart to install the Multicloud Search service
    digest: 248b2df1f70c4112e7b7f60594dd1ed4ed355fa9d42ef93d529f45093afa7c69
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:40:12.506103963Z"
    description: helm chart for multicloud topology
    digest: f3020e331550b5b1049681fe31123d710ed9b3d4502fd6ca57d4450cc9934ab8
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-07-31T18:40:12.489932893Z"
