apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-17T19:51:46.844354813Z"
    description: Helm chart for Open Cluster Management application UI
    digest: bce5e7c84785cf93ec0c0370844827f875f7fb80d520d30826bd640d02fde930
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-17T19:51:46.848008164Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: ee143cc4afe5a7de99d4428cf2a3e5201575249d9150bd993c7fffd771817c60
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-17T19:51:46.849605281Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 56635c6bfe7e658a42514360e8c220c4a8880b677e9ad851c69b19bd9bc5382f
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-06-17T19:51:46.850453466Z"
    description: A helm chart for deploying the config map watcher component.
    digest: a0af7dcae4f7e1a0c3f1bb80d1f685b8b79b392ec32141e3631afd0545f8da43
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-06-17T19:51:46.851370427Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 7114a7edc197247257fd102038e86f7c76779156f7c0d192b6359a38caaffcf5
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-17T19:51:46.852496249Z"
    description: helm chart for multicloud grc
    digest: 3c5aa9dc998172e37c87769b814c0c86062b830a03e5d7aa3df7f73f67877194
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-17T19:51:46.854391892Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 946aa9cc652d3d0bea874cf128de73e1fcb3ccdb1c81186a19bd53c84325c0c9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-17T19:51:46.8562369Z"
    description: Multi Cloud control plane ingress controller
    digest: fbf53223e2b441d137c82da43212b88d02abf0906c9fac83636e39b394108840
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-06-17T19:51:46.858380501Z"
    description: NoSQL document-oriented database.
    digest: bc5474b146a43270dd77b6b16e45e3b777bfd60d6c8999c0b2c3293e12afd523
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-17T19:51:46.85940226Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 971aeba442576d1b4ca634a0bd333cac7913359d4b4dc690c34408887303cf26
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-06-17T19:51:46.858933283Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 843e06887301d3466002368f854f1355627be1fada71851ef327934bd77dd7c5
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-17T19:51:46.860424253Z"
    description: Helm chart to install the Multicloud Search service
    digest: fba51dc63f09fb79d2fafe5599f218c6090e2afc43e5cb7726b3c3225aa20bd1
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-17T19:51:46.860915794Z"
    description: helm chart for multicloud topology
    digest: 1c0a7e05983104b686d3f80e12df829f90164ff4aa2d7a300627424b2f4d9db5
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-06-17T19:51:46.842998758Z"
