apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-12T19:01:43.162494535Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 5dfe292d37d0da6d478adba462feb0f7109138c9d20cdea5f6f66e92dbc73efc
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T19:01:43.163537707Z"
    description: Service for issuing and managing certificates.
    digest: 62ad7fc8ee91a29380fc64acee68d8ce90e4ec10b954057ae54347e99ffb5ca5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T19:01:43.164910222Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: a28a298a09e6e50088672228898afc0f650b3523c6721dcbc986890228a888a3
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-12T19:01:43.16567908Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 1dfa587ebd9e9c098ea3a320701408c673609d90a09bc017a64e5ac7d79ac264
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T19:01:43.166108675Z"
    description: helm chart for multicloud grc
    digest: 5aa178aaed694368b6124b5649a0ae88e3f804bbf9809e0b5eb53a07ff96f864
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-12T19:01:43.166911266Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: b6c3e5f85948b693a7e8363c6b32f9ae9ae42f180c6e33aaa1028b7f48f5fc92
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-12T19:01:43.168005118Z"
    description: Multi Cloud control plane ingress controller
    digest: 55a07988bd605cacec1ac4126135268f25f69353d7044e72ac7295ef53a62719
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-12T19:01:43.168919262Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 3a963e5b0635fa3af8396986c7f063865145f3ee9a12ca311ed5a4e83fd92b49
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-12T19:01:43.171052865Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 6788897d70c863181bb33b8fbfc9e4db63952a3eef09504be5339a6e31c23fea
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T19:01:43.171983975Z"
    description: helm chart for multicloud topology
    digest: 34ea119a3e3fc31d3af842a7e5acfac8d48a69bc8e3ae316a985ca71ebd048a1
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-12T19:01:43.161822329Z"
