apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-02-16T19:59:18.746559555Z"
    description: Helm chart for Open Cluster Management application UI
    digest: cb45f3c35275559f70bdc9a6aa860e7876be4bd5396f04a5383ac54cd58745d7
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.3.0.tgz
    version: 2.3.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-16T19:59:18.747556039Z"
    description: Service for issuing and managing certificates.
    digest: 894bfc17be68e3eaf22dde47077d7b857829b1d58c850a0939966dd23c42310d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.3.0.tgz
    version: 2.3.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-02-16T19:59:18.748915576Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 696792097e90e237d3ae43785d3681d0652ca08d8ce513fbc645c91a63667f78
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.3.0.tgz
    version: 2.3.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-02-16T19:59:18.749592362Z"
    description: A helm chart for deploying the config map watcher component.
    digest: d2ee75078b3cc2a494f50f62c3423351b24f307602f3d76ee043ac0eef66a959
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.3.0.tgz
    version: 2.3.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-02-16T19:59:18.750265761Z"
    description: Helm chart for Open Cluster Management Console
    digest: 3709091574b3ec51aab82b698cb18a9d1f93c11030800b693b68ed5723f29b6c
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.3.0.tgz
    version: 2.3.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-02-16T19:59:18.750643401Z"
    description: helm chart for multicloud grc
    digest: c68301269dbbc11a5a1669aaf359d8f0756f6dbba1c66d515acf3162f9a2e1d6
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.3.0.tgz
    version: 2.3.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-02-16T19:59:18.751459253Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 5912bd0cb289d5489340980df0fedc2486a8b415dac250d5bef121f968868de4
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.3.0.tgz
    version: 2.3.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-02-16T19:59:18.752482339Z"
    description: Multi Cloud control plane ingress controller
    digest: 2c605c99460420e4b8be5ff14a867aef95c4eca75bfadd961dd2a48ac243f1ff
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.3.0.tgz
    version: 2.3.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-02-16T19:59:18.753384843Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2ffd147d3ebc4623d7d6a21195c90516a37aaa25589e0dcf0f9638464d66c780
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.3.0.tgz
    version: 2.3.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-02-16T19:59:18.756969459Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 5dc3d816760e26b77883d51059b91eaa17f607b5410c56d3f5455d67485c6c4b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.3.0.tgz
    version: 2.3.0
generated: "2021-02-16T19:59:18.745909446Z"
