apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-06T19:52:57.651896644Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 7f547ea6d11db9a6f0f3b5067f32bd7b12c4caf1df1f6e8331684e4adbf67e77
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.2.tgz
    version: 2.1.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-06T19:52:57.654810777Z"
    description: Service for issuing and managing certificates.
    digest: e36bfb82663479b303efd108720b1637bbdc211d058b110acf9209bec64be87d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.2.tgz
    version: 2.1.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-06T19:52:57.656187981Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c831d3d585a51f11cb805dbe13449be65d7360e10c7cf7a1185ccda495049986
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.2.tgz
    version: 2.1.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-06T19:52:57.657827282Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 370d29274a765a40cf76c8188d3f2e520fcb15a86d36c83e8d6511c4231ebcd6
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.2.tgz
    version: 2.1.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-06T19:52:57.65935734Z"
    description: Helm chart for Open Cluster Management console UI
    digest: 9a4cc977926aa22791d258a705c95ef8f454814a7fd2627a72ae45ae7de85c85
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.2.tgz
    version: 2.1.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-06T19:52:57.660388468Z"
    description: helm chart for multicloud grc
    digest: 28a71240396b7e7ab07c08cf0d74fc6e83cd1f848054ff3bc751788a41862391
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.2.tgz
    version: 2.1.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-06T19:52:57.661701403Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: a1519daab6ba6e139d2bdbda3020412e7154918aed675c7f1e51183aeb43d27e
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.2.tgz
    version: 2.1.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-06T19:52:57.662778745Z"
    description: Multi Cloud control plane ingress controller
    digest: 625155563d4b630f72edc545e2b164232306c5ecfc7127c19d9fc95a4a0acb9d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.2.tgz
    version: 2.1.2
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-01-06T19:52:57.663739224Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: bb243f300249db48d19ed45e4916f88224ca77b335b2d3be1fcae5cbd850da12
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.2.tgz
    version: 2.1.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-06T19:52:57.664755681Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 136ceb7e923e3211b9b198ca52dea4004cd9828af89019ddfce15d7891be3b70
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.2.tgz
    version: 2.1.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-06T19:52:57.665135432Z"
    description: helm chart for multicloud topology
    digest: fd3c67d8501ee8953be413f6de72cbdf322245e2b1a08f08e4aeff768e02a866
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.2.tgz
    version: 2.1.2
generated: "2021-01-06T19:52:57.651234326Z"
