apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-31T18:45:01.472368446Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9a372e8468ebfde3c4212ce5a11d0e5df3a651f702817115f7977e005d2fd12f
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-31T18:45:01.475651351Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 05f5cf97b1b2d2b2805b2de0a74615a8cfd85f45605fadb11affb0956453259f
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-no-crds:
  - apiVersion: v1
    appVersion: 3.5.0
    created: "2020-03-31T18:45:01.476699442Z"
    description: Service for issuing and managing certificates.
    digest: f7ea3419194eb053d2e498a6b63c63d16e92de6e31cf0890c41457ec4ed74ee5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager-no-crds
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-no-crds-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-31T18:45:01.478477775Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 9a0611b6b2b71824d0d54f2860dacb2ee2a217357d6694189b4474196fcd2838
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-31T18:45:01.480060346Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 1a3a6d989f4c127741cdffcdce0889a6de4ff8710dd1ba4b2222bbc7be767084
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-31T18:45:01.48197245Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 453a049f7ab73dd997dcf172092bb65be0246dc51e9e15e353cdebe7fbcaa464
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-31T18:45:01.482477784Z"
    description: helm chart for multicloud grc
    digest: a655ea3ad34e1d30ae6e7810343344ee17370474661b28455b2fb5f37903756d
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-31T18:45:01.483304601Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: d2031fe8373e7c17169707f95d08624ba28c253eb28673f54c29660d6141fec9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-31T18:45:01.484159842Z"
    description: Multi Cloud control plane ingress controller
    digest: df45c0562b628d86fd27225d51f2c87a724af09eb6a970a83a40181085153866
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-03-31T18:45:01.486281868Z"
    description: NoSQL document-oriented database.
    digest: 1dc7c206b7415ffca9457734f231441b2210f899b717ed31a4cce98f48df0d94
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-31T18:45:01.486788382Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 828969470b93160ba4031aad3194264c9d8774f614c320356450a8445b609e8f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-31T18:45:01.487743298Z"
    description: Helm chart to install the Multicloud Search service
    digest: dd9c6b20e196bd6aae17fed161c027ac9f09fdf88b603d2be9c199b94a62ad67
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-31T18:45:01.488183554Z"
    description: helm chart for multicloud topology
    digest: 3af0603683d1a8bdaca2396d1a88f933d9d6cd00e898c399663b992eb4f5e097
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-31T18:45:01.47166557Z"
