apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-12T13:30:19.245526-04:00
    description: Helm chart for Open Cluster Management application UI
    digest: a3d24309af2a754ae417edaca18ad35e24492fbfdce75a42c5f9b4d151e04245
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-12T13:30:19.249612-04:00
    description: Service for issuing and managing certificates.
    digest: 8fef9054014c71c8c0978f34c0dc640e786c04105125815be3e455709e243c29
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-03-12T13:30:19.250526-04:00
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 5b80e4f6910ae57a9b7090bdb67e98906357fe3d019021e3b8fcfe840d7fc98a
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: 2020-03-12T13:30:19.251485-04:00
    description: A helm chart for deploying the config map watcher component.
    digest: 44deff1331603130fcb2cf8a93e65a8bd49ce15bc04d53c3fa17bc4086845b84
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    tillerVersion: '>=2.7.0'
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-12T13:30:19.252952-04:00
    description: Helm chart for Open Cluster Management console UI
    digest: 93b702ac01159c225524f98b275b601f6b01ce25789d3ad8aec9cf3267344089
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    tillerVersion: '>=2.9.1'
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-12T13:30:19.253864-04:00
    description: helm chart for multicloud grc
    digest: 41ba18d4492c364303099bf861681772b4860eaab3d4ed94294c7c406cce6fa0
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-12T13:30:19.255404-04:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 64371c728553668e827054458ea2a3b93a3f76f047b72518b5ed3ce668249635
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - appVersion: 3.4.0
    created: 2020-03-12T13:30:19.256995-04:00
    description: Multi Cloud control plane ingress controller
    digest: 12ab3072145acf9da2443b0d96ee799c08304066691776e0f666ff2a7f49c1c3
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    tillerVersion: '>=2.12.3'
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicloud-mongodb:
  - appVersion: 4.0.12
    created: 2020-03-12T13:30:19.258571-04:00
    description: NoSQL document-oriented database.
    digest: 551e5e3cd8d371dfbcedb9b9c9d8e209bc198af9e2436c7060fde72ae30882a2
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicloud-mongodb
    sources:
    - https://github.com/mongodb/mongo
    tillerVersion: '>=2.9.0'
    urls:
    - http://multiclusterhub-repo:3000/charts/multicloud-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-03-12T13:30:19.259969-04:00
    description: A helm chart for deploying the cluster lifecycle
    digest: f2bdb0074a7eaad6cc1704c2e0097dcfe6ab6db42d701b932b7ceb0fb84768db
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    tillerVersion: '>=2.12.3'
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - appVersion: 3.4.0
    created: 2020-03-12T13:30:19.261586-04:00
    description: Helm chart to install the Multicloud Search service
    digest: 5bd069315d4e6e60008bda07a1fc0f980442cdd1f22f2000fc8135d504b37098
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2020-03-12T13:30:19.261932-04:00
    description: helm chart for multicloud topology
    digest: 2ade195612b3b5c30b12e99dc65c41330dc5a0f42d560099a3e33a6f3c4f4adb
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: 2020-03-12T13:30:19.242426-04:00
