apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-04-03T17:51:50.583167093Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 9775b8b762fcc2205031f6a1a615d408ec09b84e862bb028360d37cf35e8ef6e
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-04-03T17:51:50.586440493Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: de55a9c9762ac6f56a24bc0f540aaca6eca1a5ccf17e4d9f4e1e1e21486133f3
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-no-crds:
  - apiVersion: v1
    appVersion: 3.5.0
    created: "2020-04-03T17:51:50.587550043Z"
    description: Service for issuing and managing certificates.
    digest: f7ea3419194eb053d2e498a6b63c63d16e92de6e31cf0890c41457ec4ed74ee5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager-no-crds
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-no-crds-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-04-03T17:51:50.589282291Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: dc3880345ffc2427f4faba10f60173fb16a5ae716bb2fc46738260143dcf050b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-04-03T17:51:50.590808767Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 183553658cdbde1f31ec2d4312f41d0cf67bab4a5c5881a3fed7e3aa40f25a33
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-04-03T17:51:50.592623171Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 6d57f57c52d9000df3506a29438729d40259ab2cbf1cba726cde60f45cb1bfd1
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-04-03T17:51:50.593117955Z"
    description: helm chart for multicloud grc
    digest: 9cbfdcce6c3e316fac1ee7e9c80871356118029ccf1dbbd3945e0a78e1bb2928
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-03T17:51:50.593832033Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 5cd563453bcbef2c47f9ec7a38646ee74987fe9e1476f9bbf33a3ad55301cb95
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-04-03T17:51:50.594642875Z"
    description: Multi Cloud control plane ingress controller
    digest: 7117a0963e7b6d8490d3fb9fa1481b4155467806321fc212d521dc9ed2ea47b2
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-04-03T17:51:50.596654709Z"
    description: NoSQL document-oriented database.
    digest: 3bb3244f5a8aa1fd7d01ee5b2ac3c134a3698f4a4384c070ff2ef546ffe59a37
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-03T17:51:50.597113364Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d681db883725ae7c511e8da8ad77423f70ca75edbdfa4c2263b3d7654f4bdc94
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-04-03T17:51:50.598042796Z"
    description: Helm chart to install the Multicloud Search service
    digest: 61495025aca2cd48cb0d0dc4be6e7411360c37479842f81a045cc0a1f42a93aa
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-04-03T17:51:50.598474086Z"
    description: helm chart for multicloud topology
    digest: 87768e83a731dc123a7b55e73ece95a992d6ffb08cae8ae80de27145a3ca756f
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-04-03T17:51:50.582457155Z"
