apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-07T21:40:01.408417798Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 2da61088fd92e4d671c1fd8ae6c08053ae0a15fd5cad94cd92c1562d373701de
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.2.tgz
    version: 2.1.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-07T21:40:01.409620692Z"
    description: Service for issuing and managing certificates.
    digest: c693d6d8e33c00573d3e42adea1ca14e0dabcbfaebe182a84253f819c7291534
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.2.tgz
    version: 2.1.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-07T21:40:01.411114358Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 419ad92bc1da2e5ed651e6376cdbcda551fed55f3855e0ca298c36b3d7247cb8
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.2.tgz
    version: 2.1.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-07T21:40:01.411912448Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 31c031a14703a145c25266389253a00b5df3a262a55e0ede6a46739ae23296d5
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.2.tgz
    version: 2.1.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-07T21:40:01.412548398Z"
    description: Helm chart for Open Cluster Management console UI
    digest: 432241f014080ca9774661b0e6cb01245fc936dfa0bebb57f0e0dfff1d6626fd
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.2.tgz
    version: 2.1.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-07T21:40:01.412988897Z"
    description: helm chart for multicloud grc
    digest: 71dca1874e2b2612b71ddc0a26aba49b419792f3fc2a59e364d954540c81649c
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.2.tgz
    version: 2.1.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-07T21:40:01.413822863Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 1127b5be6c14a76f4e82c980e746b83ccb8c98ba0fd0ebecd6f7ad097f86b8bd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.2.tgz
    version: 2.1.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-07T21:40:01.414907227Z"
    description: Multi Cloud control plane ingress controller
    digest: 4c0b293e0002cf9f4231a6940f28b8d2a633593914adfc6b5464b76ec8785027
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.2.tgz
    version: 2.1.2
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-01-07T21:40:01.416215625Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 79d8115b9bf8babfc33d2f98abb7b654b2be464d2f1c8f7a66fdb136fa5f797a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.2.tgz
    version: 2.1.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-07T21:40:01.418472811Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 1f689877dcdcef30217a7a5ea069949414655bd1478cc68f935aa99e2177a1a6
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.2.tgz
    version: 2.1.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-07T21:40:01.419387021Z"
    description: helm chart for multicloud topology
    digest: 4c1497ac32eae7527430d5e574769db0addd9237f42bb8f8bd7a8d00980e8dd3
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.2.tgz
    version: 2.1.2
generated: "2021-01-07T21:40:01.407721235Z"
