apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-01T15:48:13.444283377Z"
    description: Helm chart for Open Cluster Management application UI
    digest: f4d79a6707e6a17ed4e04b07b7cef16fcb2aef179f42b90f1eafe0c353e32504
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-01T15:48:13.447642535Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 18d30aeb34a87d09cec1cf9c0fa04234aaff1232acc13847d4242e972f2fa28d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-01T15:48:13.449120598Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: e6aa3722d077d91073b9281f30a13e5c819205c8f1e196be960889fff6f58672
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-07-01T15:48:13.450015418Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 705abd26d4b50a9b26ad834125adfe343f457ed847f004c590bc784d7e9add3d
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-07-01T15:48:13.452139627Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: c2b1e54fd86c7a79f0aee7dc28c7ee2267361b7d6880f4dc0056c6883059d9ea
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-01T15:48:13.453233064Z"
    description: helm chart for multicloud grc
    digest: dac4a5e45beb8e51f151ce1bd4a3754ff53fcc3e7e5215ed6a4f7a77b137f23f
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-01T15:48:13.454618049Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 79f66c51e560e75ee48c38d38f472df6e64de3f829f8f14c1d0121044c5b0f27
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-01T15:48:13.455575185Z"
    description: Multi Cloud control plane ingress controller
    digest: 4b29e3e5a2b8fc5a6f6a9c4ec27328d143db5904e60d2dbcf4eb531673a71d80
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-07-01T15:48:13.456346491Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2c08e32b52465d0b8d3d36909a07717ba1363755ec822fbe084309f09b2570ca
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-01T15:48:13.457367309Z"
    description: Helm chart to install the Multicloud Search service
    digest: 7482d359332d5911acefbb724b81915e34a26ff11557b06f7338135273b13c6b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-01T15:48:13.45783647Z"
    description: helm chart for multicloud topology
    digest: f64aa46fe9cf5e9797f50ff29353b8bb113dc5a9fc029d66d0e0eb40a8f1707f
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-07-01T15:48:13.442852924Z"
