apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:42:08.716798425Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 92b14b945d0642daa1dd7a331f10e9fafa8aaf0482a422ac9ddfa3ca22ea16ae
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-05T19:42:08.720659976Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 34c70774b0583128888fa09f393ed036d3dd5b7ba4914d047327c7268b39b284
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-05T19:42:08.722292389Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: d896029387115794d02b43e4cf8b9d07ea55b8799e7619c6347386f84828d587
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-08-05T19:42:08.723784126Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 091f7a156815972c86a5115c4b3dcae51f05521e191c68dc5127e0068a35a7c9
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-05T19:42:08.725806469Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 17487ffd6d77d818ba6ab166d6b6eaf526332fdc6d57a72b6f790b9d86348c82
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:42:08.726973623Z"
    description: helm chart for multicloud grc
    digest: 9f4c8d7f1fb2bd6e017c187e3a0aced605bca7a5ed75fa8cce48d9a891a1db41
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-05T19:42:08.728319602Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 68d4fcd723b48fe5cb131c7372be732cd94f28c6b9da6b88382261e23e0be43d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-05T19:42:08.72934384Z"
    description: Multi Cloud control plane ingress controller
    digest: 4681a125fe030a1773f17ae8c3a394f047c16ac6f739625fed244063b0cb904a
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-08-05T19:42:08.730998888Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: dc2864da365fc2ad3cec08662ede9d9688a17f2bc6d843d57ea92502ea306032
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-05T19:42:08.730190237Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2727c2a51580ccea028ae5d2e037f14c21624f9720e581b6522723a5479b55e2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-05T19:42:08.732151486Z"
    description: Helm chart to install the Multicloud Search service
    digest: 13559c29898b50a1224a226110d4ae8cec149a459989b5647b3527d51d8f6426
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:42:08.732572581Z"
    description: helm chart for multicloud topology
    digest: 58648fa9046f368fbcfa7ca0927929313d233c00d9808000bf27b55fde6a038b
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-08-05T19:42:08.715119753Z"
