apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T17:20:37.160766575Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 057b46891600adc9819b931bcc340f6392da15d2469c8dc050766e6e9000f80b
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-25T17:20:37.164814439Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 04257de114445d2013ebab7b7b691af22f5677245e8a0a42a8f291a013760e9a
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-25T17:20:37.16628289Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: cf028b61a40190695d7c1e0d2b13431af0a81e6684097c33613c239afb6b8242
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-08-25T17:20:37.167128266Z"
    description: A helm chart for deploying the config map watcher component.
    digest: f2dd029dc4320f98efb38a71238d731af2d60182d8af419ac952bc1756617f93
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-25T17:20:37.168007277Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 43060a746bbd442a94937d7e4fa7fcaebdbdc350d35618b83bed79717c924861
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T17:20:37.169463827Z"
    description: helm chart for multicloud grc
    digest: b5b63885168acde534a24cc62cfa6c825f70980356bb2eedc9611d03670d690f
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-25T17:20:37.171178221Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 2476c7d831ed1d1ec126e779ad44575fbd0f8e0bffade9a26172650c25b0b53e
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-25T17:20:37.173035738Z"
    description: Multi Cloud control plane ingress controller
    digest: 3a9b2d838a8606afabdfd00ff9f00956b09255661d3c87eac5bf730e994e642c
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-25T17:20:37.174685757Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 617faa348124b123b98013856f2d9f727301c9174bec23dfd13f63648ad12cc3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-25T17:20:37.173863439Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 5253fa9bc4fcc08063ccd5da3c8abada7260c64dde197f8ae5969a728f3dc106
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-25T17:20:37.175742822Z"
    description: Helm chart to install the Multicloud Search service
    digest: 2ed471449d5f7fe3bede823fed580590d864869e22dc9ae304323e1865dab02d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T17:20:37.176148923Z"
    description: helm chart for multicloud topology
    digest: 3af9bcdc506a8006b5cbad05ccce1054bf3387fd18b7680016a326fdb2e478cc
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-08-25T17:20:37.159233406Z"
