apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-10-13T17:54:18.965603198Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 35e5d5e82b401b96bb21e610a25c0d854719cc7974038b70999e45bd991fa3e9
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-10-13T17:54:18.969271527Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: cdafab5a49d104327979c1862a608d9875a982e02309a5ce4e46558b4113054e
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.0.tgz
    version: 2.1.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-10-13T17:54:18.970654365Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 1ce09548e32669389c6ec4f0cd7e507ae57e15951a1e236351964ee301ddc943
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.0.tgz
    version: 2.1.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-10-13T17:54:18.971473945Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 1b16b02695ec40de9af0d16b9c667f5230911d536a273f8986450d2854557cbb
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.0.tgz
    version: 2.1.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-10-13T17:54:18.972343773Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: d973c6b27e3b5c4eb9918363d17bf521b6d4d5c86d42613a20f4d1093153d604
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.0.tgz
    version: 2.1.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-10-13T17:54:18.973756108Z"
    description: helm chart for multicloud grc
    digest: 63df77ef5358e0a9ae15c8a089bba68dab93aafdeb8ed3ea68e8306d1d07543f
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-10-13T17:54:18.975562954Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: ff07c50591d10ab7e3d4295a597b59e5dc2946a320ecf8db2eb50203143d9cd5
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.0.tgz
    version: 2.1.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-10-13T17:54:18.97705603Z"
    description: Multi Cloud control plane ingress controller
    digest: d4715116446fb847722b98c1c430d0bb701250b3a5aa94e4df44c57da4725ef8
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.0.tgz
    version: 2.1.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-10-13T17:54:18.977911644Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: a082382d772eb1689fb7caf5a2be57a519c52bf63f218236bb5c9f57d2678deb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-10-13T17:54:18.978931311Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 57da7b2435a6bca29ccc02065f02ba0f60d12374699f38dac8403e8bde454015
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-10-13T17:54:18.979308533Z"
    description: helm chart for multicloud topology
    digest: 1ee4add63759cd525becf709127567c822517b265c8edeec800e30f2b8a70640
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-10-13T17:54:18.964137265Z"
