apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:20:31.342042434Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ab6590fb3ff721011666430e662cc290d9a16938d4f4377d03a3f6f22fc7c7f4
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-05T19:20:31.345381003Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 8047627ff1f69ee989291d9951855d53037e91f5499454a82a01a9a07c315c14
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-05T19:20:31.346929219Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 583d4c584712590bae6614e514b34fdddbd5cadb38d120f3fe11f8d8e7696138
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-08-05T19:20:31.347815827Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 5ab3af2778f01932e7afc97145de28ea202366048c2c3d2836b8b1a9a0d428ce
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-05T19:20:31.350130379Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 72b182d088afe4c45774140a59668ed963c03354a40686c84057473d4900581d
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:20:31.351215145Z"
    description: helm chart for multicloud grc
    digest: 958593b8455874560ecedca8ddbf61a22c10aec9ddbd0a0d6628efbb118daeb7
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-05T19:20:31.352475223Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 4c362093e1fc6f02979d73080a73a53e2047a927da205ebfb52d89465f5ea075
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-05T19:20:31.353434219Z"
    description: Multi Cloud control plane ingress controller
    digest: 97bb998732cc76abc20725eee0f9a0d8f2032103b109b4dc2e607f8bdbd3c1ac
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-08-05T19:20:31.355231019Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 89afc331353f0442b8b7652531cc40475337f26d5ec3077b2a72be223c4a942c
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-05T19:20:31.354335676Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 2727c2a51580ccea028ae5d2e037f14c21624f9720e581b6522723a5479b55e2
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-05T19:20:31.356260662Z"
    description: Helm chart to install the Multicloud Search service
    digest: 5b49b0f2270a90d1e7b3a47dcfcb2c74992bec6ba70ecc9ab5927f5fb4e893ec
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-05T19:20:31.356694415Z"
    description: helm chart for multicloud topology
    digest: 6b56ce902649cc706d774d486b81e1401f6b35a25413d4af937526f36d82e5c9
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-08-05T19:20:31.340413839Z"
