apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T20:48:22.596253659Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 265b4dcfadcf55a22e5cfe259848e43af563c6756b78c6ba9e9948a43574fb36
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-25T20:48:22.599661583Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 85ac1f2288e083da61a47c3d92f581919dd00a935ca313c9a452c70e66c72411
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-08-25T20:48:22.601046294Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c0fefd8861ab42a330e762bd00942311544be8242cbb36b3dd263dac4527823b
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-08-25T20:48:22.601836758Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 197d2d845d3d3c773ab9ad21144b24a36b119980f18e52921590a14e1918d2af
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-08-25T20:48:22.60389374Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: d9d30e55fa0933bfedf056e005efa1ddaffcfca3596078a3caff6fa02f606df0
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T20:48:22.604958245Z"
    description: helm chart for multicloud grc
    digest: 02ea8fb1d6339d3eaaea1a29d11eafbb3d5155b205389e95a0bae11c981d7a6a
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-08-25T20:48:22.606390595Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 652e68b8050e8a108b29d536380e548db0ac37c393068caebe7ad159e8146e6f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-25T20:48:22.607497682Z"
    description: Multi Cloud control plane ingress controller
    digest: 8aad7b3b2f7f093a9e49e58f3b01e2238688da321b9f38bf614d69e3993c9858
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-08-25T20:48:22.60831832Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 9c5a6b69f0f194cbbd5f39688e187eb271d6bac07785698fbea3165e7962e18f
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.2.tgz
    version: 2.0.2
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-08-25T20:48:22.609349696Z"
    description: Helm chart to install the Multicloud Search service
    digest: c522ac0b5aa5cc2f08fcac490655c32a1d323c7261a72ea8679a5e2c6c67bb7e
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-08-25T20:48:22.609765839Z"
    description: helm chart for multicloud topology
    digest: 34de60c1ff8d76362a09d83b7ddd3aa46de878f34fa1481eadb8acbb1fa560f2
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-08-25T20:48:22.594730646Z"
