apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-05T14:38:16.681839416Z"
    description: Helm chart for Open Cluster Management application UI
    digest: e900a8483a62fc798d483485d330bc8fa6a9e0f22b8aad9ec6aed767198a5b5d
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-05T14:38:16.685122091Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 56d1c05872092e8cabefa625d2f31a5a3d0c9bab50e2394b6323c68d434fc47d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-05T14:38:16.686540589Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: b7392b9c000fa0fb8d650768ae0ecdce7718a7176c26a0e872824281a1bbd3c6
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-06-05T14:38:16.687414813Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 4a815cc4100723ebdc6c098f271f316ecb887b5607ecf4245090c7bd1a780bf4
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-06-05T14:38:16.689625125Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 97248ddc10dfd973e5de25f025d2b486a7c8c1068a5ec33f12dabf49300a2d51
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-05T14:38:16.690720934Z"
    description: helm chart for multicloud grc
    digest: ec23eb60bd58c536196c52a23039d155779b0e75c08693c2aa9ecad0487647e7
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-05T14:38:16.69188132Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 0f942ad2d775405ad2687ebafcc3c5e2e6c4753ef373cae32c946c03ef13308a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-05T14:38:16.692844352Z"
    description: Multi Cloud control plane ingress controller
    digest: 9d59e04698e615be49074483c97fa935a59e607bb34f988e2e554edb200e1dfa
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-06-05T14:38:16.694929857Z"
    description: NoSQL document-oriented database.
    digest: a2641072e0716e3b5cb780de80667d3329d262a05e5deafbeeeaa344814dc456
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-05T14:38:16.695762964Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 971aeba442576d1b4ca634a0bd333cac7913359d4b4dc690c34408887303cf26
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-06-05T14:38:16.695370223Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: d598950a7c4519d3d56ed7849ffb38df87039ff1ae78b6a15160d39fe38ce69b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-05T14:38:16.696640355Z"
    description: Helm chart to install the Multicloud Search service
    digest: 54dc1708185472e02dc39277af6d2dc031ab01e14c97e62a51d6498b81b2725c
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-05T14:38:16.697053826Z"
    description: helm chart for multicloud topology
    digest: eaa0610ccf2191a8d4ee4be815add74e034b76c978e7856d43c49173668e09bf
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-06-05T14:38:16.680556627Z"
