apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-05-05T13:28:50.689376991Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 36b58ec757a51daee6b208fb71cc5dd0efe26bd81640eb6e5203e0c1f9c4c8cc
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.4.tgz
    version: 2.2.4
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-05-05T13:28:50.690465639Z"
    description: Service for issuing and managing certificates.
    digest: 66600d2921d7ca923c903da9d8b4c8542e4a201a7baeaeecf5aa05d5ee8c5675
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.4.tgz
    version: 2.2.4
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-05-05T13:28:50.693891085Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 99c3e67c4eb3034a5c9195ed3a83041dbdd5e097493bdc1388cea91e41d9f90f
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.4.tgz
    version: 2.2.4
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-05-05T13:28:50.695492742Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 7c35e15bdd5aff750fc46b654bcb4f2a316ad114427e90fcd108acfccd0b007b
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.4.tgz
    version: 2.2.4
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-05-05T13:28:50.696212666Z"
    description: Helm chart for Open Cluster Management Console
    digest: d6cbbdf1fb4169f4065c028f5067c088c7d8064b3492ba67d3705e6bd16a68b0
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.4.tgz
    version: 2.2.4
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-05-05T13:28:50.696666889Z"
    description: helm chart for multicloud grc
    digest: 00e71c05e7c39da27c0193dac6930f7e060dabf32c4389d64dff4edf541b456f
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.4.tgz
    version: 2.2.4
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-05-05T13:28:50.697476219Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: f711cce9ba899913fb5e9cd34cb301f4792973c0ea26085869cfe109055e396d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.4.tgz
    version: 2.2.4
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-05-05T13:28:50.69847463Z"
    description: Multi Cloud control plane ingress controller
    digest: 0765857c7e160e53f98a21fc586a493cc97dd20f6d6247e3a4f1d452a1d42e67
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.4.tgz
    version: 2.2.4
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-05-05T13:28:50.699419937Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: add7e98093ee52c63154248c77378c766af89f65bf5092c20c435ecd7bb96b49
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.4.tgz
    version: 2.2.4
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-05-05T13:28:50.70088178Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 95748949a1455c91277460091483fd404983fb7c08793634f7cd8ed2d7c81dc8
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.4.tgz
    version: 2.2.4
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-05-05T13:28:50.701309361Z"
    description: helm chart for multicloud topology
    digest: 963f2f4be446d6e072a6b80568ddfe760a23012a66bd2587b00954d572056a0f
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.4.tgz
    version: 2.2.4
generated: "2021-05-05T13:28:50.688694555Z"
