apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-12T20:34:06.332300952Z"
    description: Helm chart for Open Cluster Management application UI
    digest: ca7f458423ce380d0c2030f33207ab695d4c1bb1416c2aada6a7bf0869d781ef
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.2.0.tgz
    version: 2.2.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T20:34:06.333397767Z"
    description: Service for issuing and managing certificates.
    digest: ad1399327870ead7312536b4910428e0ebb5947b40ea25d723c32ff8bfb38c70
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.2.0.tgz
    version: 2.2.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-12T20:34:06.334736907Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: d7c0b671d19c729ea2992f01a58505dbee090e6f7a0862ebebf8287abfb5dc22
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.2.0.tgz
    version: 2.2.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-12T20:34:06.335491587Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 63f6bb627e78583df955852e41b6a5f1f323b22657427968dc10ab8f58fd4c06
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.2.0.tgz
    version: 2.2.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-12T20:34:06.336218805Z"
    description: Helm chart for Open Cluster Management Console
    digest: d8c6f27e03fed4273c8e011cbbcf99dacdfe9414cf0eb808f8efb8207d322a93
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.2.0.tgz
    version: 2.2.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T20:34:06.336611321Z"
    description: helm chart for multicloud grc
    digest: 18665d49dee5fc143f07738d8360a6cb0fa6130d763197bf3af552098ce02a3c
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.2.0.tgz
    version: 2.2.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-12T20:34:06.337468822Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 388db4419f21f5860a9df35eecfcdeb310b6841ea45f94d6847d1208ea601f1b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.2.0.tgz
    version: 2.2.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-12T20:34:06.338540335Z"
    description: Multi Cloud control plane ingress controller
    digest: 78c49fa825ca44bf04187dadbfbcd547fec55c67511226a70aa2c3326b0ac7fa
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.2.0.tgz
    version: 2.2.0
  rcm:
  - apiVersion: v1
    appVersion: "2.2"
    created: "2021-01-12T20:34:06.339998982Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 4d88bbacafb7b5fd7881235ccaaf583e4c46054b4cb11394fbe1f72691d84c5a
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.2.0.tgz
    version: 2.2.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.2.0
    created: "2021-01-12T20:34:06.342507385Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: fb90ce537d17beb4a66c1b1f393f3108cdb919c8f9082ab67aeaa30801d2b517
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHACM
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.2.0.tgz
    version: 2.2.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-12T20:34:06.343654802Z"
    description: helm chart for multicloud topology
    digest: 5daaca0de6680a31fe3a1c0511c5ad2467a78d911e43afb21289d371baa437f8
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.2.0.tgz
    version: 2.2.0
generated: "2021-01-12T20:34:06.331607043Z"
