apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-30T15:39:33.781469329Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 1a1a22631a284af43a52f6da55cd29a70b39228f174b867b6397851a7824142f
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.0.tgz
    version: 2.1.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-30T15:39:33.785037041Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: d0a93385b5bdbc7abb2aafedb93f19a1122bac55368bc8d2fe62905c93f90142
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.0.tgz
    version: 2.1.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-09-30T15:39:33.786427533Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: b1b4cdf6df7b74b1a18528fe05e682de4a1ebd3f89e4f76f16e05b59a10a32a1
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.0.tgz
    version: 2.1.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-09-30T15:39:33.787227672Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 3a222019c424363249e442fcbce70147fd6dd7b4739647768313bb500394e9db
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.0.tgz
    version: 2.1.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-09-30T15:39:33.788146915Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 32aa55fabd03c22d24013d04a67fd2ee2ba2a217d80c2c121ad204e23f31968b
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.0.tgz
    version: 2.1.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-30T15:39:33.789476369Z"
    description: helm chart for multicloud grc
    digest: b046aa1398bcab7e24e1f923d21220b477717a4bea566cb2e39e652d0088b7bf
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.0.tgz
    version: 2.1.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-09-30T15:39:33.79123731Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 9163661c9e979ca915e8c303bab2803ecc706b5374c3873386e0ca666131bb4b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.0.tgz
    version: 2.1.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-09-30T15:39:33.79281026Z"
    description: Multi Cloud control plane ingress controller
    digest: 000ee91fa9908b7d1d68c42458a59acb426211b68cc023ba8172ce32bf9cd72a
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.0.tgz
    version: 2.1.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-09-30T15:39:33.793676953Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 20f72a8e658727990f8f33f59099e53cb1b03357b4b9d324f96d1fa3f05fd8c4
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-09-30T15:39:33.794648361Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 6af63856a0d298404ecbe2503da7e66c3908931f04a0baf1a226e8dae5bbd86d
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.0.tgz
    version: 2.1.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-09-30T15:39:33.795026554Z"
    description: helm chart for multicloud topology
    digest: 0b49b6b49dad9dd77daeb9203680f400d58ca00aadc3ce45a6375180f7b034d1
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.0.tgz
    version: 2.1.0
generated: "2020-09-30T15:39:33.779924565Z"
