apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:14:27.870623242Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 46cbedbd5546511c73cc44d29a523dcf0c88ff6ec1b96057a6895f46fd336bbf
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-31T18:14:27.874256343Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 4fd35538175e5c686d813d3d6cb78063e0649adf8a6649e5070b9301b3552cde
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-07-31T18:14:27.875764354Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: a349ce67ae0cce223b31209ef985c0a79cbcabb5b4f79e3cc12cec7f1322cf23
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-07-31T18:14:27.876694726Z"
    description: A helm chart for deploying the config map watcher component.
    digest: aa36a54f1893eca056a421bc2c4c05ce98432f082e5251f6388895ccb8f1287a
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-07-31T18:14:27.877633154Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: f30628b2d3fbc84b3805df7acf2d5934b25eded8fd95418403df2efd7559e4da
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:14:27.879026257Z"
    description: helm chart for multicloud grc
    digest: 2d3588c1adad364e2f9d29d19c30bd86490cdeadf51be6364d4be44323c9afd0
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-31T18:14:27.880851493Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 33f82c6aae56468ce073ace6db8ba099588b9680769c88f7138ce56195256adb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-31T18:14:27.882541335Z"
    description: Multi Cloud control plane ingress controller
    digest: ffff7f471d075538bb6cb2fd4b9a5d1b23bdcd22dbdbe3e2836bc215ba756f76
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-07-31T18:14:27.884279832Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 567cee01c5138482ffdfbe68c8bd84040f04e0abe1575ab2c080f2960ec056eb
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-07-31T18:14:27.883386398Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: c39e5b3c2669aaed3c47dd86420abec625faa3a81fe0508b4a26aafa4d350082
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-07-31T18:14:27.885324773Z"
    description: Helm chart to install the Multicloud Search service
    digest: 27c97e637e8879450a3b98b2d4cb13576deaccf0f9be22f218fe02310b6700cf
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-31T18:14:27.885727462Z"
    description: helm chart for multicloud topology
    digest: b708a9d7189ef8b9484e2e26d76d9912a064c96a62a3cf34295a5c5d32e7cb19
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-07-31T18:14:27.869047654Z"
