apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-27T14:41:46.689998984Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 24641e110301f41cb992716d2ced96d43c5f10dd36fa28513313e8c91c2a6766
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.3.tgz
    version: 2.1.3
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-27T14:41:46.69102261Z"
    description: Service for issuing and managing certificates.
    digest: 108f6ada46be4de4593832b8ef3b98a23eb4881c96aa28568cb8c91b2ee3fa2c
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.3.tgz
    version: 2.1.3
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-01-27T14:41:46.692324222Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: a42fe349bd3e4df814d7214e3712bdfffca4f288fd333d6c4ba0c8f5a2300a32
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.3.tgz
    version: 2.1.3
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-01-27T14:41:46.693029592Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 47356552841b5d670f27e9494cc7d165c0087b282724b0c9a74a490ee9a64e55
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.3.tgz
    version: 2.1.3
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-01-27T14:41:46.693679434Z"
    description: Helm chart for Open Cluster Management console UI
    digest: 6357de9fdcf647601cea8e678f3fd5d72aa560f4e0b37e30e014fba432d421c1
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.3.tgz
    version: 2.1.3
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-27T14:41:46.694103963Z"
    description: helm chart for multicloud grc
    digest: 78a36843a8dd0aa1c7e22a3f8009a4cb5452f7577955ac63121024adef37970f
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.3.tgz
    version: 2.1.3
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-01-27T14:41:46.694941743Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: b5a78b3327d14992e01c7519428e651a7d32049bb9f8dcccb6662c8191573988
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.3.tgz
    version: 2.1.3
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-01-27T14:41:46.695931279Z"
    description: Multi Cloud control plane ingress controller
    digest: 49b6cef63ff2ac1f17b674945b715d7e9ad69bd223b54522137b1678a9939560
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.3.tgz
    version: 2.1.3
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-01-27T14:41:46.697012702Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 1b14ac07b58d4e03d13b824c070425e4cf907ffbc8d08e98dbfedc834ef3b9e3
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.3.tgz
    version: 2.1.3
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-27T14:41:46.699145113Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: a1c6a4f1b718cbf07b599665b3e97183b7697051b66a3ad94b24d3b6aeaea151
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.3.tgz
    version: 2.1.3
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-01-27T14:41:46.700200253Z"
    description: helm chart for multicloud topology
    digest: 8417a83c7bd35046eb8f3463b38fefdcfed36993abf28ef67c594112e315b00b
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.3.tgz
    version: 2.1.3
generated: "2021-01-27T14:41:46.689375183Z"
