apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-05-20T15:42:35.407629497Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 19f886e7f4108d93b21afe7c0be56926d8f11403566c04aed5dee40b5394b884
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.7.tgz
    version: 2.1.7
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-05-20T15:42:35.408818965Z"
    description: Service for issuing and managing certificates.
    digest: bacbc4751c9ef3739a114db9a3e26b67baaccd7ca0806a52afa099dc3d9b150c
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.7.tgz
    version: 2.1.7
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2021-05-20T15:42:35.410275238Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 07d8258484c66f77690ee91ed32f63b04bb1fbb49b6a708a77fe6dc903b5bf0d
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.7.tgz
    version: 2.1.7
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2021-05-20T15:42:35.41219767Z"
    description: A helm chart for deploying the config map watcher component.
    digest: fd2c7b46e8e91f69914c5ef60963f61ca3b6b2de1b8f41359663e6d98702a102
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.7.tgz
    version: 2.1.7
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-05-20T15:42:35.413565789Z"
    description: Helm chart for Open Cluster Management console UI
    digest: b5653320b6af030405f81b16ab07e60679761d2be4a03f8b62c4a60b3a03ce37
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.7.tgz
    version: 2.1.7
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-05-20T15:42:35.414780092Z"
    description: helm chart for multicloud grc
    digest: 7c1ce885cd2fa038688524e4f918aafad2aba6735a31f30d0e78f1cbf4ffc55d
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.7.tgz
    version: 2.1.7
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-05-20T15:42:35.415652422Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 073216fbbdeed09e16c2c105360bbf1ed47ac255b1307c61df42d21856dc47c9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.7.tgz
    version: 2.1.7
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2021-05-20T15:42:35.416652875Z"
    description: Multi Cloud control plane ingress controller
    digest: 7dfbc9015bb922d7544d7b660f1ab1549ab3ee4c8aaae769955aa589a6599141
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.7.tgz
    version: 2.1.7
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2021-05-20T15:42:35.417364454Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: bec4dd6147c81dc2ddc8bc7e937a7b6348a70b59f91eedf282e32699b4d35da9
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.7.tgz
    version: 2.1.7
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-05-20T15:42:35.418316937Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: 6cca400b91c25d6a72ade8d7573847a461f75a6540a5b399ae83cb303ffca72f
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.7.tgz
    version: 2.1.7
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-05-20T15:42:35.418761043Z"
    description: helm chart for multicloud topology
    digest: 4315030c6427d2c3bf39df6da29e812bdb477a738e747657b04611e5b5b37d3b
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.7.tgz
    version: 2.1.7
generated: "2021-05-20T15:42:35.406834754Z"
