apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-30T20:34:48.349851353Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 29ad2779469cbb5f79d89b831295c035d988587f6cdcaf89e5eb79e7e141ac61
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-30T20:34:48.353231336Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 55298013112060452d2c57ede0a0aab5b7c1d86c8b533c4d22bc30eddb54b37d
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-no-crds:
  - apiVersion: v1
    appVersion: 3.5.0
    created: "2020-03-30T20:34:48.354279589Z"
    description: Service for issuing and managing certificates.
    digest: f7ea3419194eb053d2e498a6b63c63d16e92de6e31cf0890c41457ec4ed74ee5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager-no-crds
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-no-crds-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-30T20:34:48.356118898Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 255e18cc920b8a0eadebc585f6bd749594ba35b1cdde19f8519724bb5335179c
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-30T20:34:48.357630643Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 70262d5eb82bbc8d365888fd874149290e7881cbc4bb4972e886d0682a67ea25
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-30T20:34:48.35950517Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 20e9e21d76b1c0f285e97e04da1be0e72422636648b64223d3c0c01531f0d5e5
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-30T20:34:48.360009034Z"
    description: helm chart for multicloud grc
    digest: 0e95fcfeacdcdafc9ef23444ceb2c27efbd720c6178f3f341cda8134509fb709
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-30T20:34:48.360752841Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 9aec93ca4c385cbf813ad6892ea5d3501b843082b17d8d3e7fddc00fdbf8c64b
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-30T20:34:48.36174227Z"
    description: Multi Cloud control plane ingress controller
    digest: e0ba30de74e761cb5f18663121bff1767dd9cbdd2769bd0728bd7bf48a824c32
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-03-30T20:34:48.36402768Z"
    description: NoSQL document-oriented database.
    digest: c107fd666a7216485b81b1013b83dd3a24c297eb696ba853c14ff1cdfa0b4da1
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-30T20:34:48.364528706Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 96ac9fb164ad2ebfecb27dacb6cf13a2b6f0c16407dc47a51e9a4b2224400c78
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-30T20:34:48.365496679Z"
    description: Helm chart to install the Multicloud Search service
    digest: 455b7e54830620148b29e8d976fe7e6e28ef406e2ce78ddc5597ba163380b424
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-30T20:34:48.365940914Z"
    description: helm chart for multicloud topology
    digest: 13cdecda7faa66a2e2028b40ea7faa1478f5b9018b49b1a2c74068ed2f52d137
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-30T20:34:48.348924599Z"
