apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-01T18:38:12.859803363Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 52088188bc0f7ab40d56245c07c22c8aacfab5141a76734b6ba6582e617217a1
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-01T18:38:12.863313611Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 6b5e689291ca8156791a9e6e87c5380a4abb309259b982f36950ba61702073f9
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.6.0.tgz
    version: 3.6.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.2
    created: "2020-06-01T18:38:12.864656544Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: fad963a4cfa5de47c4d6b5063cffa2524b83e2cf23cc13b2ca1108931d2172cb
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.6.0.tgz
    version: 3.6.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.6.0
    created: "2020-06-01T18:38:12.86566288Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 239f2321ee57b8317c646656520c5d806ecc27319a349339e828af931b1ed486
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.6.0.tgz
    version: 3.6.0
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-06-01T18:38:12.867051908Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 44dfe446637a1f0699e616a15d2973f6eb799c8cac1a83fd5d14ba9da3621071
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.0.0.tgz
    version: 2.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-01T18:38:12.86823902Z"
    description: helm chart for multicloud grc
    digest: 1534a0cb8093905cabe5cedaba47bb9ba1fe23a59335aaffc0f026cad6e35d0e
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.0.0.tgz
    version: 2.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-01T18:38:12.869785627Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 5c25b4a26dea96687998ff77da25a6f1c8b34e0426cf31aa07336160396ded14
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.6.0.tgz
    version: 3.6.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-01T18:38:12.871308386Z"
    description: Multi Cloud control plane ingress controller
    digest: 3c71957b86c4d12e9f0f8424047ed09901ae6e22ee275ad31d954507e139536d
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-06-01T18:38:12.873491812Z"
    description: NoSQL document-oriented database.
    digest: d22a2ed4695b0ce7a8ca255cd5985782afa2a56d717bafb0ce8538b23b4bad1f
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-06-01T18:38:12.874421887Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 971aeba442576d1b4ca634a0bd333cac7913359d4b4dc690c34408887303cf26
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  - apiVersion: v1
    appVersion: "2.0"
    created: "2020-06-01T18:38:12.873933589Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 26e11809fbb74e2f2ec7cfc8d78b140e330b6ca937c6ab87a481403b913bdcdd
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.0.0.tgz
    version: 2.0.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-06-01T18:38:12.87533984Z"
    description: Helm chart to install the Multicloud Search service
    digest: df9a74acac869ae9672b04329fbb4d4a0f511a8e18d20d8ec1ff34e6a2aabb82
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-06-01T18:38:12.875792546Z"
    description: helm chart for multicloud topology
    digest: 9b4ea8c538f9cbcdd00db1fab6c8e38b9a976300be0e2a6443bf3d7bbdbe1615
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-06-01T18:38:12.8584681Z"
