apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-03T19:24:53.80655078Z"
    description: Helm chart for Open Cluster Management application UI
    digest: f349c5e758b751c822bc5523d625c5ee1594991b131a9be9eddd36061aad195b
    keywords:
    - ui
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-2.1.2.tgz
    version: 2.1.2
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-03T19:24:53.812279371Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 47d4d61a422412005925c70e08c64de04466ec5f12334cc3757a9dbbcd6aeac0
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-2.1.2.tgz
    version: 2.1.2
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.3
    created: "2020-12-03T19:24:53.813741212Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: 1099a298dcc1a30c374e39392e36759b67e4e1214a353f4b5f64f871e320164d
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-2.1.2.tgz
    version: 2.1.2
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.7.0
    created: "2020-12-03T19:24:53.814572469Z"
    description: A helm chart for deploying the config map watcher component.
    digest: fa7d46c29fba91ee66c8771abfa0ec9257150f0e9ca10e987dc3309b6d9fe66f
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-2.1.2.tgz
    version: 2.1.2
  console-chart:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2020-12-03T19:24:53.815391647Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 2.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: 43ae56039538e684dd11f398b8a5dacecbe63f0f41347ec2cd38c86c966b0540
    keywords:
    - ui
    kubeVersion: '>=1.10.0-0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-2.1.2.tgz
    version: 2.1.2
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-03T19:24:53.815860358Z"
    description: helm chart for multicloud grc
    digest: 45f9c63ca3cccd2167fccbeef23bd4ae4ce5b5ebbd1a428fa585953704c2c011
    keywords:
    - acm
    - grc
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-2.1.2.tgz
    version: 2.1.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-12-03T19:24:53.816694428Z"
    description: A helm chart for deploying the Red Hat Visual Web Terminal
    digest: 2d5fa9be8cc94f207848f9ab5c0dc934c0435115a919cea9f72cdfb4344be074
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-2.1.2.tgz
    version: 2.1.2
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-12-03T19:24:53.817754225Z"
    description: Multi Cloud control plane ingress controller
    digest: 85abf46e8683344afef7dc1e470e3fc936e12f70c97efe05588f56842cfe1ab2
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-2.1.2.tgz
    version: 2.1.2
  rcm:
  - apiVersion: v1
    appVersion: "2.1"
    created: "2020-12-03T19:24:53.818739212Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: 8ccff56bc46f0c123c829d9613233491a7f5fd0fcfc8e048c5baca637e562b35
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0-0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-2.1.2.tgz
    version: 2.1.2
  search-prod:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-12-03T19:24:53.819857402Z"
    description: Helm chart to install the Open Cluster Management Search service
    digest: cc8f537e78ffa862ccb47103281ded9f8b3f41161d8eca6c092e48cc04f4752c
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-2.1.2.tgz
    version: 2.1.2
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-12-03T19:24:53.820301201Z"
    description: helm chart for multicloud topology
    digest: 1cf52f63561b665b484a7d4e073834587c6b19cf73fbe22ec694abec3ce8647b
    keywords:
    - acm
    - topology
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-2.1.2.tgz
    version: 2.1.2
generated: "2020-12-03T19:24:53.80589108Z"
