name: Update Charts

on: 
  # trigger from charts
  repository_dispatch:
    types: [ chart-change ]
  
  # manual trigger
  workflow_dispatch:

jobs:
  chart-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.HUB_REPO_TOKEN }}

      - name: Auto Trigger info
        if: github.event_name == 'repository_dispatch'
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_ENV
          echo "Chart update run automatically via $GITHUB_EVENT_NAME" >> $GITHUB_ENV
          echo "Initiated by - $GITHUB_ACTOR" >> $GITHUB_ENV
          echo "Chart Repo - ${{ github.event.client_payload.repository }}" >> $GITHUB_ENV
          echo "Chart Branch - ${{ github.event.client_payload.ref }}" >> $GITHUB_ENV
          echo "Chart SHA - ${{ github.event.client_payload.sha }}" >> $GITHUB_ENV
          echo "Workflow URL - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Manual Trigger info
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_ENV
          echo "Chart update run manually via $GITHUB_EVENT_NAME" >> $GITHUB_ENV
          echo "Initiated by - $GITHUB_ACTOR" >> $GITHUB_ENV
          echo "Workflow URL - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Update charts
        run: bash cicd-scripts/chart-sync.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: ${{ env.commit_message }}
          commit_options: '--signoff'
          file_pattern: multiclusterhub/charts currentSHAs.csv
          skip_fetch: true
          commit_user_name: GitHub Actions
          commit_user_email: noreply@github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>          
